// `Armorer Guildmage` — "{B}, {T}: Target creature gets +1/+0 until end of turn.\n{G}, {T}: Target creature gets +0/+1 until end of turn."
// Two tap abilities on one Wizard, each a Caller of Gales (D202) / Wyluli
// Wolf (D271) pump-or-grant on the tap carrier. GENERATED by
// gen-guildmages.cjs — edit the table, never this file. D272.

import { ARMORER_GUILDMAGE } from '../../../data/fixtures/engineCards';
import type { CardData } from '../../../data/cardTypes';
import type { CardScript } from '../api';
import type { EventBody } from '../../types/events';

function printed(card: CardData, expected: string): string {
  const actual = card.faces[0]?.oracleText;
  if (actual !== expected) {
    throw new Error(
      card.name + ' reads "' + actual + '" and its script was written for "' + expected + '". ' +
        'Re-read the card before re-registering it (D90).',
    );
  }
  return expected;
}

const PRINTED = printed(
  ARMORER_GUILDMAGE,
  '{B}, {T}: Target creature gets +1/+0 until end of turn.\n{G}, {T}: Target creature gets +0/+1 until end of turn.',
);
const LINES = PRINTED.split('\n');

export const ARMORER_GUILDMAGE_SCRIPT: CardScript = {
  oracleId: ARMORER_GUILDMAGE.oracleId,
  name: ARMORER_GUILDMAGE.name,
  activated: [
    {
      ref: `${ARMORER_GUILDMAGE.oracleId}#a0`,
      text: LINES[0] as string,
      resolve: (ctx, _self, obj): readonly EventBody[] => {
        const target = obj.targets[0];
        if (!target || target.kind !== 'card') return [];
        if (ctx.state.cards[target.id]?.zone.kind !== 'battlefield') return [];
        return [
          {
            t: 'PtModifiedUntilEndOfTurn',
            card: target.id,
            power: 1,
            toughness: 0,
            keywords: [],
          },
        ];
      },
    },
    {
      ref: `${ARMORER_GUILDMAGE.oracleId}#a1`,
      text: LINES[1] as string,
      resolve: (ctx, _self, obj): readonly EventBody[] => {
        const target = obj.targets[0];
        if (!target || target.kind !== 'card') return [];
        if (ctx.state.cards[target.id]?.zone.kind !== 'battlefield') return [];
        return [
          {
            t: 'PtModifiedUntilEndOfTurn',
            card: target.id,
            power: 0,
            toughness: 1,
            keywords: [],
          },
        ];
      },
    },
  ],
};
