// `Dega Disciple` — each of the two tap abilities lands on the target
// and is gone at cleanup; the Wizard taps for either. GENERATED by
// gen-guildmages.cjs (D272).

import { describe, expect, test } from 'vitest';
import { replay, stateHash } from '../../log';
import { createRegistry } from '../registry';
import { DEGA_DISCIPLE_SCRIPT } from './degaDisciple';
import { advanceUntil, deps, must, put, startedGame } from '../../testing/harness';
import { derive } from '../../derive';
import type { Game } from '../../game';
import type { InstanceId } from '../../types/ids';

const MAGE = 'Dega Disciple';
const BEARS = 'Grizzly Bears';

function settle(g: Game): void {
  advanceUntil(g, (s) => s.stack.length === 0 && s.pendingTriggers.length === 0, 20_000);
}

/** Past summoning sickness, the ability at `index` used on my own Bears. */
function used(index: 0 | 1, symbol: 'W' | 'U' | 'B' | 'R' | 'G'): { g: Game; mage: InstanceId; bears: InstanceId } {
  const g = startedGame({
    players: 2,
    decks: [[MAGE, BEARS], []],
    scripts: createRegistry([DEGA_DISCIPLE_SCRIPT]),
  });
  const bears = put(g, 'p1', BEARS);
  const mage = put(g, 'p1', MAGE);
  settle(g);
  advanceUntil(g, (s) => s.turn.turnNumber >= 3 && s.priority.awaiting === null, 60_000);
  must(g.submit({ t: 'ManualAddMana', player: 'p1', target: 'p1', symbol, amount: 1 }));
  must(g.submit({ t: 'ActivateAbility', player: 'p1', card: mage, abilityIndex: index }));
  must(g.submit({ t: 'ChooseTargets', player: 'p1', targets: [{ kind: 'card', id: bears }] }));
  settle(g);
  return { g, mage, bears };
}

function chars(g: Game, id: InstanceId): ReturnType<typeof derive> {
  const d = deps(createRegistry([DEGA_DISCIPLE_SCRIPT]));
  return derive(g.state, d.oracle, d.scripts, id);
}

function pt(g: Game, id: InstanceId): { power: number | null; toughness: number | null } {
  const got = chars(g, id);
  return { power: got.power, toughness: got.toughness };
}

describe('Dega Disciple', () => {
  test('ability 0 shrinks -2/-0 and taps the Wizard', () => {
    const { g, mage, bears } = used(0, 'B');
    expect(pt(g, bears)).toEqual({ power: 0, toughness: 2 });
    expect(g.state.cards[mage]?.tapped).toBe(true);
  });

  test('ability 1 pumps +2/+0', () => {
    const { g, mage, bears } = used(1, 'R');
    expect(pt(g, bears)).toEqual({ power: 4, toughness: 2 });
    expect(g.state.cards[mage]?.tapped).toBe(true);
  });

  test('cleanup takes ability 0 back (CR 514.2)', () => {
    const { g, bears } = used(0, 'B');
    advanceUntil(g, (s) => s.turn.turnNumber >= 4, 60_000);
    expect(pt(g, bears)).toEqual({ power: 2, toughness: 2 });
  });

  test('replays to the same hash', () => {
    const { g } = used(1, 'R');
    advanceUntil(g, (s) => s.turn.turnNumber >= 4, 60_000);
    expect(stateHash(replay(g.log, g.seed))).toBe(g.hash());
  });
});
