// `Tramway Station` — the Sphere shape with a COLOURED cost: enters tapped (D134's
// built-in), a two-colour mana line (the engine's), and `{2}{B}{R}`, the tap
// and ITSELF for a card (this def, #a1). The five shipped Spheres pay {1}{C};
// this is the same three printed lines one cost over, generated by growing
// D258's table rather than hand-writing a sixth copy. D261.

import { TRAMWAY_STATION } from '../../../data/fixtures/engineCards';
import { drawEvents } from '../../effects';
import type { CardData } from '../../../data/cardTypes';
import type { CardScript } from '../api';
import type { EventBody } from '../../types/events';

function printed(card: CardData, expected: string): string {
  const actual = card.faces[0]?.oracleText;
  if (actual !== expected) {
    throw new Error(
      `${card.name} reads "${actual}" and its script was written for "${expected}". ` +
        'Re-read the card before re-registering it (D90).',
    );
  }
  return expected;
}

const PRINTED = printed(
  TRAMWAY_STATION,
  'This land enters tapped.\n{T}: Add {B} or {R}.\n{2}{B}{R}, {T}, Sacrifice this land: Draw a card.',
);
const TEXT = PRINTED.split('\n')[2] as string;

export const TRAMWAY_STATION_SCRIPT: CardScript = {
  oracleId: TRAMWAY_STATION.oracleId,
  name: TRAMWAY_STATION.name,
  activated: [
    {
      // `#a1`: the mana line parses as ability 0, the draw as ability 1.
      ref: `${TRAMWAY_STATION.oracleId}#a1`,
      text: TEXT,
      resolve: (ctx, _self, obj): readonly EventBody[] => drawEvents(ctx.state, obj.controller, 1),
    },
  ],
};
