// ⚠️ GENERATED by scripts/make-engine-fixtures.cjs — DO NOT EDIT BY HAND.
//
// Verbatim `CardData` records from the real Scryfall data, so the engine tests
// exercise the same text the app will. Hand-editing a value here silently
// turns a rules test into a test of the edit — the D15b failure mode.
// Regenerate with `node scripts/make-engine-fixtures.cjs` (needs a synced DB).
//
// `scripts/battery-carddb.cjs` cross-checks these against the live database, so
// a Scryfall rewording fails there rather than rotting silently here.

import type { CardData } from '../cardTypes';

export const PLAINS: CardData = {
  "scryfallId": "00293ce4-3475-4064-8510-9e8c02faf3bf",
  "oracleId": "bc71ebf6-2056-41f7-be35-b2e5c34afa99",
  "name": "Plains",
  "layout": "normal",
  "faces": [
    {
      "name": "Plains",
      "manaCost": "",
      "typeLine": "Basic Land — Plains",
      "oracleText": "({T}: Add {W}.)",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Andreas Rocha",
      "imageId": "00293ce4-3475-4064-8510-9e8c02faf3bf"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "cma",
  "collectorNumber": "292",
  "commanderLegality": "legal",
  "singleImage": true
};

export const ISLAND: CardData = {
  "scryfallId": "000f1f50-08e5-4d83-8159-98f06a0e2279",
  "oracleId": "b2c6aa39-2d2a-459c-a555-fb48ba993373",
  "name": "Island",
  "layout": "normal",
  "faces": [
    {
      "name": "Island",
      "manaCost": "",
      "typeLine": "Basic Land — Island",
      "oracleText": "({T}: Add {U}.)",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Lucas Graciano",
      "imageId": "000f1f50-08e5-4d83-8159-98f06a0e2279"
    }
  ],
  "colorIdentity": [
    "U"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "eld",
  "collectorNumber": "255",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SWAMP: CardData = {
  "scryfallId": "00030770-5e99-4943-819d-8d807c24cc14",
  "oracleId": "56719f6a-1a6c-4c0a-8d21-18f7d7350b68",
  "name": "Swamp",
  "layout": "normal",
  "faces": [
    {
      "name": "Swamp",
      "manaCost": "",
      "typeLine": "Basic Land — Swamp",
      "oracleText": "({T}: Add {B}.)",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Adam Paquette",
      "imageId": "00030770-5e99-4943-819d-8d807c24cc14"
    }
  ],
  "colorIdentity": [
    "B"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "jmp",
  "collectorNumber": "59",
  "commanderLegality": "legal",
  "singleImage": true
};

export const MOUNTAIN: CardData = {
  "scryfallId": "005a993c-5111-4364-9fba-75b3d94a8296",
  "oracleId": "a3fb7228-e76b-4e96-a40e-20b5fed75685",
  "name": "Mountain",
  "layout": "normal",
  "faces": [
    {
      "name": "Mountain",
      "manaCost": "",
      "typeLine": "Basic Land — Mountain",
      "oracleText": "({T}: Add {R}.)",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Douglas Shuler",
      "imageId": "005a993c-5111-4364-9fba-75b3d94a8296"
    }
  ],
  "colorIdentity": [
    "R"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "2ed",
  "collectorNumber": "298",
  "commanderLegality": "legal",
  "singleImage": true
};

export const FOREST: CardData = {
  "scryfallId": "0000419b-0bba-4488-8f7a-6194544ce91e",
  "oracleId": "b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6",
  "name": "Forest",
  "layout": "normal",
  "faces": [
    {
      "name": "Forest",
      "manaCost": "",
      "typeLine": "Basic Land — Forest",
      "oracleText": "({T}: Add {G}.)",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "David Robert Hovey",
      "imageId": "0000419b-0bba-4488-8f7a-6194544ce91e"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "blb",
  "collectorNumber": "280",
  "commanderLegality": "legal",
  "singleImage": true
};

export const WASTES: CardData = {
  "scryfallId": "02729948-9b74-453f-a268-2f29b48a29ee",
  "oracleId": "05d24b0c-904a-46b6-b42a-96a4d91a0dd4",
  "name": "Wastes",
  "layout": "normal",
  "faces": [
    {
      "name": "Wastes",
      "manaCost": "",
      "typeLine": "Basic Land",
      "oracleText": "{T}: Add {C}.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Jason Felix",
      "imageId": "02729948-9b74-453f-a268-2f29b48a29ee"
    }
  ],
  "colorIdentity": [],
  "cmc": 0,
  "keywords": [],
  "setCode": "plst",
  "collectorNumber": "OGW-183",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SNOW_COVERED_FOREST: CardData = {
  "scryfallId": "1c59fc48-704b-4187-b9d3-2a2cff6dd54b",
  "oracleId": "5f0d3be8-e63e-4ade-ae58-6b0c14f2ce6d",
  "name": "Snow-Covered Forest",
  "layout": "normal",
  "faces": [
    {
      "name": "Snow-Covered Forest",
      "manaCost": "",
      "typeLine": "Basic Snow Land — Forest",
      "oracleText": "({T}: Add {G}.)",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Titus Lunter",
      "imageId": "1c59fc48-704b-4187-b9d3-2a2cff6dd54b"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "mh1",
  "collectorNumber": "254",
  "commanderLegality": "legal",
  "singleImage": true
};

export const COMMAND_TOWER: CardData = {
  "scryfallId": "0548fb60-c843-4f8f-a029-6f10efc63a41",
  "oracleId": "0895c9b7-ae7d-4bb3-af17-3b75deb50a25",
  "name": "Command Tower",
  "layout": "normal",
  "faces": [
    {
      "name": "Command Tower",
      "manaCost": "",
      "typeLine": "Land",
      "oracleText": "{T}: Add one mana of any color in your commander's color identity.",
      "flavorText": "\"Of course the Triskelion is a big gaudy target. And anyone who's confident enough to think about taking it out is someone we want on our radar.\"\n—Nick Fury, director of S.H.I.E.L.D.",
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Leon Tukker",
      "imageId": "0548fb60-c843-4f8f-a029-6f10efc63a41"
    }
  ],
  "colorIdentity": [],
  "cmc": 0,
  "keywords": [],
  "setCode": "msc",
  "collectorNumber": "233",
  "commanderLegality": "legal",
  "singleImage": true
};

export const TUNDRA: CardData = {
  "scryfallId": "05ab141b-ba27-4127-a973-ff0cd72d2c64",
  "oracleId": "02418479-9455-417f-a6a1-004356faff37",
  "name": "Tundra",
  "layout": "normal",
  "faces": [
    {
      "name": "Tundra",
      "manaCost": "",
      "typeLine": "Land — Plains Island",
      "oracleText": "({T}: Add {W} or {U}.)",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Jesper Myrfors",
      "imageId": "05ab141b-ba27-4127-a973-ff0cd72d2c64"
    }
  ],
  "colorIdentity": [
    "U",
    "W"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "30a",
  "collectorNumber": "577",
  "commanderLegality": "legal",
  "singleImage": true
};

export const ANCIENT_TOMB: CardData = {
  "scryfallId": "09721698-35a4-48a2-8896-fe036a642345",
  "oracleId": "23467047-6dba-4498-b783-1ebc4f74b8c2",
  "name": "Ancient Tomb",
  "layout": "normal",
  "faces": [
    {
      "name": "Ancient Tomb",
      "manaCost": "",
      "typeLine": "Land",
      "oracleText": "{T}: Add {C}{C}. This land deals 2 damage to you.",
      "flavorText": "On the slab runes were deeply graven:\nBALIN\nSON OF FUNDIN\nLORD OF MORIA",
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Anastasia Balakchina",
      "imageId": "09721698-35a4-48a2-8896-fe036a642345"
    }
  ],
  "colorIdentity": [],
  "cmc": 0,
  "keywords": [],
  "setCode": "ltc",
  "collectorNumber": "387z",
  "commanderLegality": "legal",
  "singleImage": true
};

export const BOROS_GARRISON: CardData = {
  "scryfallId": "2cbd1e97-e156-4a28-b2fc-1454ddb2fe95",
  "oracleId": "8fa3ac81-3dfe-4565-be99-5554f7597b4b",
  "name": "Boros Garrison",
  "layout": "normal",
  "faces": [
    {
      "name": "Boros Garrison",
      "manaCost": "",
      "typeLine": "Land",
      "oracleText": "This land enters tapped.\nWhen this land enters, return a land you control to its owner's hand.\n{T}: Add {R}{W}.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Darrell Riche",
      "imageId": "2cbd1e97-e156-4a28-b2fc-1454ddb2fe95"
    }
  ],
  "colorIdentity": [
    "R",
    "W"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "prm",
  "collectorNumber": "102369",
  "commanderLegality": "legal",
  "singleImage": true
};

export const GEMSTONE_MINE: CardData = {
  "scryfallId": "03736bdf-c5ec-4254-8c6c-b39c125e2d23",
  "oracleId": "0c828f10-4775-492f-9224-1e2814ad2cad",
  "name": "Gemstone Mine",
  "layout": "normal",
  "faces": [
    {
      "name": "Gemstone Mine",
      "manaCost": "",
      "typeLine": "Land",
      "oracleText": "This land enters with three mining counters on it.\n{T}, Remove a mining counter from this land: Add one mana of any color. If there are no mining counters on this land, sacrifice it.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Brom",
      "imageId": "03736bdf-c5ec-4254-8c6c-b39c125e2d23"
    }
  ],
  "colorIdentity": [],
  "cmc": 0,
  "keywords": [],
  "setCode": "wc98",
  "collectorNumber": "bs164",
  "commanderLegality": "legal",
  "singleImage": true
};

export const REFLECTING_POOL: CardData = {
  "scryfallId": "0bd6e6aa-c0b2-4ab1-9165-6cba8b93da13",
  "oracleId": "67f43ac6-2a58-4b53-b5d7-0330e2a252e2",
  "name": "Reflecting Pool",
  "layout": "normal",
  "faces": [
    {
      "name": "Reflecting Pool",
      "manaCost": "",
      "typeLine": "Land",
      "oracleText": "{T}: Add one mana of any type that a land you control could produce.",
      "flavorText": "\"This is the Window of the Sunset, fairest of all the falls of Ithilien, land of many fountains.\"\n—Faramir",
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Marco Gorlei",
      "imageId": "0bd6e6aa-c0b2-4ab1-9165-6cba8b93da13"
    }
  ],
  "colorIdentity": [],
  "cmc": 0,
  "keywords": [],
  "setCode": "ltc",
  "collectorNumber": "403",
  "commanderLegality": "legal",
  "singleImage": true
};

export const CAVERN_OF_SOULS: CardData = {
  "scryfallId": "09f9b3b8-090e-4152-8d44-52d92375905b",
  "oracleId": "89ca686a-7c72-4d8f-9290-e89635624a83",
  "name": "Cavern of Souls",
  "layout": "normal",
  "faces": [
    {
      "name": "Cavern of Souls",
      "manaCost": "",
      "typeLine": "Land",
      "oracleText": "As this land enters, choose a creature type.\n{T}: Add {C}.\n{T}: Add one mana of any color. Spend this mana only to cast a creature spell of the chosen type, and that spell can't be countered.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Pedro Correa",
      "imageId": "09f9b3b8-090e-4152-8d44-52d92375905b"
    }
  ],
  "colorIdentity": [],
  "cmc": 0,
  "keywords": [],
  "setCode": "lci",
  "collectorNumber": "410c",
  "commanderLegality": "legal",
  "singleImage": true
};

export const BOJUKA_BOG: CardData = {
  "scryfallId": "01769b12-4841-4a1a-a089-e061442203ed",
  "oracleId": "04b7362d-0490-4cb0-b5d7-2a7732f659ce",
  "name": "Bojuka Bog",
  "layout": "normal",
  "faces": [
    {
      "name": "Bojuka Bog",
      "manaCost": "",
      "typeLine": "Land",
      "oracleText": "This land enters tapped.\nWhen this land enters, exile target player's graveyard.\n{T}: Add {B}.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Howard Lyon",
      "imageId": "01769b12-4841-4a1a-a089-e061442203ed"
    }
  ],
  "colorIdentity": [
    "B"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "c20",
  "collectorNumber": "259",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SOL_RING: CardData = {
  "scryfallId": "04002706-2236-4b79-bdea-4f263e43cb9c",
  "oracleId": "6ad8011d-3471-4369-9d68-b264cc027487",
  "name": "Sol Ring",
  "layout": "normal",
  "faces": [
    {
      "name": "Sol Ring",
      "manaCost": "{1}",
      "typeLine": "Artifact",
      "oracleText": "{T}: Add {C}{C}.",
      "flavorText": "\"Meadowlarks sing in sun-touched skies\nAnd breezes kiss where Eirdu lies.\"\n—Verselet of Lorwyn",
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Daria Aksenova",
      "imageId": "04002706-2236-4b79-bdea-4f263e43cb9c"
    }
  ],
  "colorIdentity": [],
  "cmc": 1,
  "keywords": [],
  "setCode": "ecc",
  "collectorNumber": "57",
  "commanderLegality": "legal",
  "singleImage": true
};

export const ARCANE_SIGNET: CardData = {
  "scryfallId": "01b186af-8825-4257-80fd-9c1ecdb21414",
  "oracleId": "0bc7f093-bef0-4f1a-852c-4b75ebf54838",
  "name": "Arcane Signet",
  "layout": "normal",
  "faces": [
    {
      "name": "Arcane Signet",
      "manaCost": "{2}",
      "typeLine": "Artifact",
      "oracleText": "{T}: Add one mana of any color in your commander's color identity.",
      "flavorText": "It started as a mere drop of water. The Magic Mirror crystallized it into much more.",
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Dan Murayama Scott",
      "imageId": "01b186af-8825-4257-80fd-9c1ecdb21414"
    }
  ],
  "colorIdentity": [],
  "cmc": 2,
  "keywords": [],
  "setCode": "c21",
  "collectorNumber": "234",
  "commanderLegality": "legal",
  "singleImage": true
};

export const MOX_DIAMOND: CardData = {
  "scryfallId": "28028830-83ed-45e2-b495-3b9ad9d3e988",
  "oracleId": "f3c5978a-70fa-431f-933b-b954bd0db0ea",
  "name": "Mox Diamond",
  "layout": "normal",
  "faces": [
    {
      "name": "Mox Diamond",
      "manaCost": "{0}",
      "typeLine": "Artifact",
      "oracleText": "If this artifact would enter, you may discard a land card instead. If you do, put this artifact onto the battlefield. If you don't, put it into its owner's graveyard.\n{T}: Add one mana of any color.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Dan Frazier",
      "imageId": "28028830-83ed-45e2-b495-3b9ad9d3e988"
    }
  ],
  "colorIdentity": [],
  "cmc": 0,
  "keywords": [],
  "setCode": "sth",
  "collectorNumber": "138",
  "commanderLegality": "legal",
  "singleImage": true
};

export const LIGHTNING_GREAVES: CardData = {
  "scryfallId": "047de2fe-6fc1-40c5-98d4-6203b4a83445",
  "oracleId": "ca204b66-8d0c-431a-8d34-282f7c2d17da",
  "name": "Lightning Greaves",
  "layout": "normal",
  "faces": [
    {
      "name": "Lightning Greaves",
      "manaCost": "{2}",
      "typeLine": "Artifact — Equipment",
      "oracleText": "Equipped creature has haste and shroud. (It can't be the target of spells or abilities.)\nEquip {0}",
      "flavorText": "After lightning struck the cliffs, the ore became iron, the iron became steel, and the steel became greaves. The lightning never left.",
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Jeremy Jarvis",
      "imageId": "047de2fe-6fc1-40c5-98d4-6203b4a83445"
    }
  ],
  "colorIdentity": [],
  "cmc": 2,
  "keywords": [
    "Equip"
  ],
  "setCode": "cma",
  "collectorNumber": "220",
  "commanderLegality": "legal",
  "singleImage": true
};

export const DARKSTEEL_MYR: CardData = {
  "scryfallId": "0f5712cf-c6a9-4a2e-90db-8ca17c621724",
  "oracleId": "f90fe86c-5cca-483b-93c2-6e856fa01c88",
  "name": "Darksteel Myr",
  "layout": "normal",
  "faces": [
    {
      "name": "Darksteel Myr",
      "manaCost": "{3}",
      "typeLine": "Artifact Creature — Myr",
      "oracleText": "Indestructible (Damage and effects that say \"destroy\" don't destroy this creature. If its toughness is 0 or less, it still dies.)",
      "flavorText": null,
      "power": "0",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Randis Albion",
      "imageId": "0f5712cf-c6a9-4a2e-90db-8ca17c621724"
    }
  ],
  "colorIdentity": [],
  "cmc": 3,
  "keywords": [
    "Indestructible"
  ],
  "setCode": "som",
  "collectorNumber": "151",
  "commanderLegality": "legal",
  "singleImage": true
};

export const LLANOWAR_ELVES: CardData = {
  "scryfallId": "01c6f877-6b00-4d57-8a88-36cd3b16edbc",
  "oracleId": "68954295-54e3-4303-a6bc-fc4547a4e3a3",
  "name": "Llanowar Elves",
  "layout": "normal",
  "faces": [
    {
      "name": "Llanowar Elves",
      "manaCost": "{G}",
      "typeLine": "Creature — Elf Druid",
      "oracleText": "{T}: Add {G}.",
      "flavorText": "One bone broken for every twig snapped underfoot.\n—Llanowar penalty for trespassing",
      "power": "1",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Kev Walker",
      "imageId": "01c6f877-6b00-4d57-8a88-36cd3b16edbc"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 1,
  "keywords": [],
  "setCode": "m12",
  "collectorNumber": "182",
  "commanderLegality": "legal",
  "singleImage": true
};

export const BIRDS_OF_PARADISE: CardData = {
  "scryfallId": "0003aa31-d42e-4972-9fb9-086aefe29a2c",
  "oracleId": "d3a0b660-358c-41bd-9cd2-41fbf3491b1a",
  "name": "Birds of Paradise",
  "layout": "normal",
  "faces": [
    {
      "name": "Birds of Paradise",
      "manaCost": "{G}",
      "typeLine": "Creature — Bird",
      "oracleText": "Flying\n{T}: Add one mana of any color.",
      "flavorText": null,
      "power": "0",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Mark Poole",
      "imageId": "0003aa31-d42e-4972-9fb9-086aefe29a2c"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 1,
  "keywords": [
    "Flying"
  ],
  "setCode": "sld",
  "collectorNumber": "176",
  "commanderLegality": "legal",
  "singleImage": true
};

export const BLOOM_TENDER: CardData = {
  "scryfallId": "0b5f1455-8124-408f-9ca5-9b281ec1708f",
  "oracleId": "0c23fefe-9891-4dd8-9bb1-eebdb3274e31",
  "name": "Bloom Tender",
  "layout": "normal",
  "faces": [
    {
      "name": "Bloom Tender",
      "manaCost": "{1}{G}",
      "typeLine": "Creature — Elf Druid",
      "oracleText": "Vivid — {T}: For each color among permanents you control, add one mana of that color.",
      "flavorText": null,
      "power": "1",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Yuyuharu",
      "imageId": "0b5f1455-8124-408f-9ca5-9b281ec1708f"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 2,
  "keywords": [
    "Vivid"
  ],
  "setCode": "ecl",
  "collectorNumber": "390",
  "commanderLegality": "legal",
  "singleImage": true
};

export const GRIZZLY_BEARS: CardData = {
  "scryfallId": "10c845b8-40f1-44df-9e91-dab7606f6271",
  "oracleId": "14c8f55d-d177-4c25-a931-ebeb9e6062a0",
  "name": "Grizzly Bears",
  "layout": "normal",
  "faces": [
    {
      "name": "Grizzly Bears",
      "manaCost": "{1}{G}",
      "typeLine": "Creature — Bear",
      "oracleText": "",
      "flavorText": "Don't try to outrun one of Dominaria's grizzlies; it'll catch you, knock you down, and eat you. Of course, you could run up a tree. In that case you'll get a nice view before it knocks the tree down and eats you.",
      "power": "2",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Una Fricker",
      "imageId": "10c845b8-40f1-44df-9e91-dab7606f6271"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 2,
  "keywords": [],
  "setCode": "6ed",
  "collectorNumber": "236",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SCATHE_ZOMBIES: CardData = {
  "scryfallId": "01326c97-d1f0-46cf-a84b-2a3d3420aa3d",
  "oracleId": "e0fefaf0-da20-4d58-8db7-019dba16c780",
  "name": "Scathe Zombies",
  "layout": "normal",
  "faces": [
    {
      "name": "Scathe Zombies",
      "manaCost": "{2}{B}",
      "typeLine": "Creature — Zombie",
      "oracleText": "",
      "flavorText": "\"They groaned, they stirred, they all uprose,\nNor spake, nor moved their eyes;\nIt had been strange, even in a dream,\nTo have seen those dead men rise.\"\n—Samuel Taylor Coleridge,\n\"The Rime of the Ancient Mariner\"",
      "power": "2",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "B"
      ],
      "artist": "Kev Walker",
      "imageId": "01326c97-d1f0-46cf-a84b-2a3d3420aa3d"
    }
  ],
  "colorIdentity": [
    "B"
  ],
  "cmc": 3,
  "keywords": [],
  "setCode": "9ed",
  "collectorNumber": "160★",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SILVERCOAT_LION: CardData = {
  "scryfallId": "9d33e866-cfd8-44e6-8070-df8df1ce965d",
  "oracleId": "e3c0b11e-7340-4e0a-98b7-91b38439d4f9",
  "name": "Silvercoat Lion",
  "layout": "normal",
  "faces": [
    {
      "name": "Silvercoat Lion",
      "manaCost": "{1}{W}",
      "typeLine": "Creature — Cat",
      "oracleText": "",
      "flavorText": "\"In the wild, white fur like mine is an aberration. We lack natural camouflage, but the inability to hide encourages other strengths.\"\n—Ajani Goldmane",
      "power": "2",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Terese Nielsen",
      "imageId": "9d33e866-cfd8-44e6-8070-df8df1ce965d"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 2,
  "keywords": [],
  "setCode": "m13",
  "collectorNumber": "35",
  "commanderLegality": "legal",
  "singleImage": true
};

export const AIR_ELEMENTAL: CardData = {
  "scryfallId": "09b3086b-d737-4b26-ae1a-d03fa4553ccf",
  "oracleId": "7744bae4-a8b7-44a5-9b4c-0048ad4cc448",
  "name": "Air Elemental",
  "layout": "normal",
  "faces": [
    {
      "name": "Air Elemental",
      "manaCost": "{3}{U}{U}",
      "typeLine": "Creature — Elemental",
      "oracleText": "Flying",
      "flavorText": "\"El viento del este, un entrometido en los dominios del clima del oeste, es un tirano impasible con una daga afilada guardada en su espalda lista para una estocada traicionera.\"\n—Joseph Conrad, *El espejo del mar*",
      "power": "4",
      "toughness": "4",
      "loyalty": null,
      "defense": null,
      "colors": [
        "U"
      ],
      "artist": "Kev Walker",
      "imageId": "09b3086b-d737-4b26-ae1a-d03fa4553ccf"
    }
  ],
  "colorIdentity": [
    "U"
  ],
  "cmc": 5,
  "keywords": [
    "Flying"
  ],
  "setCode": "ps11",
  "collectorNumber": "26",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SERRA_ANGEL: CardData = {
  "scryfallId": "0845c45d-1ce4-4d06-a165-30972f1d59ca",
  "oracleId": "4b7ac066-e5c7-43e6-9e7e-2739b24a905d",
  "name": "Serra Angel",
  "layout": "normal",
  "faces": [
    {
      "name": "Serra Angel",
      "manaCost": "{3}{W}{W}",
      "typeLine": "Creature — Angel",
      "oracleText": "Flying\nVigilance (Attacking doesn't cause this creature to tap.)",
      "flavorText": "Born with wings of light and a sword of faith, this heavenly incarnation embodies both fury and purity.",
      "power": "4",
      "toughness": "4",
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Rebecca Guay",
      "imageId": "0845c45d-1ce4-4d06-a165-30972f1d59ca"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 5,
  "keywords": [
    "Flying",
    "Vigilance"
  ],
  "setCode": "o90p",
  "collectorNumber": "8",
  "commanderLegality": "legal",
  "singleImage": true
};

export const GIANT_SPIDER: CardData = {
  "scryfallId": "072bcf42-6e13-4388-ac47-f91aaa7029d1",
  "oracleId": "e740ce2f-2134-473c-afa1-1b6d2d1e38ef",
  "name": "Giant Spider",
  "layout": "normal",
  "faces": [
    {
      "name": "Giant Spider",
      "manaCost": "{3}{G}",
      "typeLine": "Creature — Spider",
      "oracleText": "Reach (This creature can block creatures with flying.)",
      "flavorText": "Watching the spider's web\n—Llanowar expression meaning \"focusing on the wrong thing\"",
      "power": "2",
      "toughness": "4",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Randy Gallegos",
      "imageId": "072bcf42-6e13-4388-ac47-f91aaa7029d1"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 4,
  "keywords": [
    "Reach"
  ],
  "setCode": "9ed",
  "collectorNumber": "244",
  "commanderLegality": "legal",
  "singleImage": true
};

export const COLOSSAL_DREADMAW: CardData = {
  "scryfallId": "76ac5b70-47db-4cdb-91e7-e5c18c42e516",
  "oracleId": "08c7db90-c0cf-4482-b7ee-bb033e5996d2",
  "name": "Colossal Dreadmaw",
  "layout": "normal",
  "faces": [
    {
      "name": "Colossal Dreadmaw",
      "manaCost": "{4}{G}{G}",
      "typeLine": "Creature — Dinosaur",
      "oracleText": "Trample (This creature can deal excess combat damage to the player or planeswalker it's attacking.)",
      "flavorText": "If you feel the ground quake, run. If you hear its bellow, flee. If you see its teeth, it's too late.",
      "power": "6",
      "toughness": "6",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Jesper Ejsing",
      "imageId": "76ac5b70-47db-4cdb-91e7-e5c18c42e516"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 6,
  "keywords": [
    "Trample"
  ],
  "setCode": "xln",
  "collectorNumber": "180",
  "commanderLegality": "legal",
  "singleImage": true
};

export const VAMPIRE_NIGHTHAWK: CardData = {
  "scryfallId": "0a1934ab-3171-4fc6-8033-ad998899ba73",
  "oracleId": "feb244f8-bcb1-44cf-9940-2719221a7309",
  "name": "Vampire Nighthawk",
  "layout": "normal",
  "faces": [
    {
      "name": "Vampire Nighthawk",
      "manaCost": "{1}{B}{B}",
      "typeLine": "Creature — Vampire Shaman",
      "oracleText": "Flying\nDeathtouch (Any amount of damage this deals to a creature is enough to destroy it.)\nLifelink (Damage dealt by this creature also causes you to gain that much life.)",
      "flavorText": null,
      "power": "2",
      "toughness": "3",
      "loyalty": null,
      "defense": null,
      "colors": [
        "B"
      ],
      "artist": "Jason Chan",
      "imageId": "0a1934ab-3171-4fc6-8033-ad998899ba73"
    }
  ],
  "colorIdentity": [
    "B"
  ],
  "cmc": 3,
  "keywords": [
    "Deathtouch",
    "Flying",
    "Lifelink"
  ],
  "setCode": "fdn",
  "collectorNumber": "186",
  "commanderLegality": "legal",
  "singleImage": true
};

export const TYPHOID_RATS: CardData = {
  "scryfallId": "035533c6-ed13-488c-a9bc-5c7087472e84",
  "oracleId": "d6ee6cc1-902d-4f56-afa5-6fa4813bfbbc",
  "name": "Typhoid Rats",
  "layout": "normal",
  "faces": [
    {
      "name": "Typhoid Rats",
      "manaCost": "{B}",
      "typeLine": "Creature — Rat",
      "oracleText": "Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.)",
      "flavorText": "Kidnappers caught in Havengul are given two choices: languish in prison or become rat catchers. The smart ones go to prison.",
      "power": "1",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "B"
      ],
      "artist": "Kev Walker",
      "imageId": "035533c6-ed13-488c-a9bc-5c7087472e84"
    }
  ],
  "colorIdentity": [
    "B"
  ],
  "cmc": 1,
  "keywords": [
    "Deathtouch"
  ],
  "setCode": "cns",
  "collectorNumber": "130",
  "commanderLegality": "legal",
  "singleImage": true
};

export const WHITE_KNIGHT: CardData = {
  "scryfallId": "042b8d98-59b8-4fba-96b0-608e416c487f",
  "oracleId": "ddb021df-ae4a-4ac1-8353-d0b375761714",
  "name": "White Knight",
  "layout": "normal",
  "faces": [
    {
      "name": "White Knight",
      "manaCost": "{W}{W}",
      "typeLine": "Creature — Human Knight",
      "oracleText": "First strike (This creature deals combat damage before creatures without first strike.)\nProtection from black (This creature can't be blocked, targeted, dealt damage, or enchanted by anything black.)",
      "flavorText": "\"When good men die their goodness does not perish, / But lives though they are gone.\"\n—Euripides, *Termenidae*, trans. Morgan",
      "power": "2",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Daniel Gelon",
      "imageId": "042b8d98-59b8-4fba-96b0-608e416c487f"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 2,
  "keywords": [
    "First strike",
    "Protection"
  ],
  "setCode": "prm",
  "collectorNumber": "35950",
  "commanderLegality": "legal",
  "singleImage": true
};

export const BOROS_SWIFTBLADE: CardData = {
  "scryfallId": "0279d460-5ade-4017-9635-ece28a5ba79d",
  "oracleId": "377e4dad-866b-4e02-8c10-072bf7f000be",
  "name": "Boros Swiftblade",
  "layout": "normal",
  "faces": [
    {
      "name": "Boros Swiftblade",
      "manaCost": "{R}{W}",
      "typeLine": "Creature — Human Soldier",
      "oracleText": "Double strike",
      "flavorText": "When the Boros Legion attacks, swiftblades enter the fray first. They pick off the archers and mages, softening the enemy front before the flame-kin and giants go in.",
      "power": "1",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "R",
        "W"
      ],
      "artist": "Doug Chaffee",
      "imageId": "0279d460-5ade-4017-9635-ece28a5ba79d"
    }
  ],
  "colorIdentity": [
    "R",
    "W"
  ],
  "cmc": 2,
  "keywords": [
    "Double strike"
  ],
  "setCode": "hop",
  "collectorNumber": "82",
  "commanderLegality": "legal",
  "singleImage": true
};

export const BOGGART_BRUTE: CardData = {
  "scryfallId": "042f10fb-5c19-4890-80ba-ea2c28805f0b",
  "oracleId": "880793a2-84b0-4ae1-9bb8-6e942e3dc723",
  "name": "Boggart Brute",
  "layout": "normal",
  "faces": [
    {
      "name": "Boggart Brute",
      "manaCost": "{2}{R}",
      "typeLine": "Creature — Goblin Warrior",
      "oracleText": "Menace (This creature can't be blocked except by two or more creatures.)",
      "flavorText": "He has the biggest bashing stick, so it's a safe bet he's the leader.",
      "power": "3",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "R"
      ],
      "artist": "Igor Kieryluk",
      "imageId": "042f10fb-5c19-4890-80ba-ea2c28805f0b"
    }
  ],
  "colorIdentity": [
    "R"
  ],
  "cmc": 3,
  "keywords": [
    "Menace"
  ],
  "setCode": "plst",
  "collectorNumber": "ORI-133",
  "commanderLegality": "legal",
  "singleImage": true
};

export const WALL_OF_OMENS: CardData = {
  "scryfallId": "0596155d-8f83-40ca-be31-9a0df1ced65e",
  "oracleId": "5f601f48-d24b-4883-9fde-b3f620e7c9ea",
  "name": "Wall of Omens",
  "layout": "normal",
  "faces": [
    {
      "name": "Wall of Omens",
      "manaCost": "{1}{W}",
      "typeLine": "Creature — Wall",
      "oracleText": "Defender\nWhen this creature enters, draw a card.",
      "flavorText": "\"I search for a vision of Zendikar that does not include the Eldrazi.\"\n—Expedition journal entry",
      "power": "0",
      "toughness": "4",
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "James Paick",
      "imageId": "0596155d-8f83-40ca-be31-9a0df1ced65e"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 2,
  "keywords": [
    "Defender"
  ],
  "setCode": "ddk",
  "collectorNumber": "4",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SCALED_BEHEMOTH: CardData = {
  "scryfallId": "017ef6eb-7a2b-4730-bf21-a2289d4c07ad",
  "oracleId": "abb39d0e-bf11-4982-b06a-ca7be16bce2c",
  "name": "Scaled Behemoth",
  "layout": "normal",
  "faces": [
    {
      "name": "Scaled Behemoth",
      "manaCost": "{4}{G}{G}",
      "typeLine": "Creature — Crocodile",
      "oracleText": "Hexproof (This creature can't be the target of spells or abilities your opponents control.)",
      "flavorText": "Surviving an encounter with it is proof enough that an initiate is ready for the Trial of Strength.",
      "power": "6",
      "toughness": "7",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Marco Nelor",
      "imageId": "017ef6eb-7a2b-4730-bf21-a2289d4c07ad"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 6,
  "keywords": [
    "Hexproof"
  ],
  "setCode": "cmr",
  "collectorNumber": "251",
  "commanderLegality": "legal",
  "singleImage": true
};

export const KOR_FIREWALKER: CardData = {
  "scryfallId": "2de6cd02-1ad1-465f-b795-e5549d90788d",
  "oracleId": "fb37ff1c-7461-4a16-b27f-6eef0db937fe",
  "name": "Kor Firewalker",
  "layout": "normal",
  "faces": [
    {
      "name": "Kor Firewalker",
      "manaCost": "{W}{W}",
      "typeLine": "Creature — Kor Soldier",
      "oracleText": "Protection from red\nWhenever a player casts a red spell, you may gain 1 life.",
      "flavorText": "\"A river of lava is just another river to cross.\"",
      "power": "2",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Matt Stewart",
      "imageId": "2de6cd02-1ad1-465f-b795-e5549d90788d"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 2,
  "keywords": [
    "Protection"
  ],
  "setCode": "td0",
  "collectorNumber": "B6",
  "commanderLegality": "legal",
  "singleImage": true
};

export const RAGING_GOBLIN: CardData = {
  "scryfallId": "165dc9fc-22b3-48ac-b446-5599af75917e",
  "oracleId": "30997b43-fc13-41d3-8064-1ccc2cb6fd2b",
  "name": "Raging Goblin",
  "layout": "normal",
  "faces": [
    {
      "name": "Raging Goblin",
      "manaCost": "{R}",
      "typeLine": "Creature — Goblin Berserker",
      "oracleText": "Haste (This creature can attack and {T} as soon as it comes under your control.)",
      "flavorText": "He raged at the world, at his family, at his life. But mostly he just raged.",
      "power": "1",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "R"
      ],
      "artist": "Jeff Miracola",
      "imageId": "165dc9fc-22b3-48ac-b446-5599af75917e"
    }
  ],
  "colorIdentity": [
    "R"
  ],
  "cmc": 1,
  "keywords": [
    "Haste"
  ],
  "setCode": "8ed",
  "collectorNumber": "212",
  "commanderLegality": "legal",
  "singleImage": true
};

export const CHILD_OF_NIGHT: CardData = {
  "scryfallId": "1796088b-83b5-4151-8dcb-90df21e9a283",
  "oracleId": "c650a7bc-e350-44a0-a698-d4a233d66156",
  "name": "Child of Night",
  "layout": "normal",
  "faces": [
    {
      "name": "Child of Night",
      "manaCost": "{1}{B}",
      "typeLine": "Creature — Vampire",
      "oracleText": "Lifelink",
      "flavorText": "Sins that would be too gruesome in the light of day are made more pleasing in the dark of night.",
      "power": "2",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "B"
      ],
      "artist": "Ash Wood",
      "imageId": "1796088b-83b5-4151-8dcb-90df21e9a283"
    }
  ],
  "colorIdentity": [
    "B"
  ],
  "cmc": 2,
  "keywords": [
    "Lifelink"
  ],
  "setCode": "plst",
  "collectorNumber": "IMA-85",
  "commanderLegality": "legal",
  "singleImage": true
};

export const BULL_HIPPO: CardData = {
  "scryfallId": "044785ad-0f05-4944-aab3-49236727078d",
  "oracleId": "4d62a448-b6a5-43b1-a281-9e9361a5524a",
  "name": "Bull Hippo",
  "layout": "normal",
  "faces": [
    {
      "name": "Bull Hippo",
      "manaCost": "{3}{G}",
      "typeLine": "Creature — Hippo",
      "oracleText": "Islandwalk (This creature can't be blocked as long as defending player controls an Island.)",
      "flavorText": "The merfolk may rule the waters, but hippos have never had much respect for authority.",
      "power": "3",
      "toughness": "3",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Heather Hudson",
      "imageId": "044785ad-0f05-4944-aab3-49236727078d"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 4,
  "keywords": [
    "Landwalk",
    "Islandwalk"
  ],
  "setCode": "7ed",
  "collectorNumber": "233",
  "commanderLegality": "legal",
  "singleImage": true
};

export const AMBUSH_VIPER: CardData = {
  "scryfallId": "066e94a1-90c2-43f9-8449-8a6d59bd751a",
  "oracleId": "8957f7c2-040c-4048-9f21-efa7c97682b7",
  "name": "Ambush Viper",
  "layout": "normal",
  "faces": [
    {
      "name": "Ambush Viper",
      "manaCost": "{1}{G}",
      "typeLine": "Creature — Snake",
      "oracleText": "Flash\nDeathtouch",
      "flavorText": null,
      "power": "2",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Alan Pollack",
      "imageId": "066e94a1-90c2-43f9-8449-8a6d59bd751a"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 2,
  "keywords": [
    "Flash",
    "Deathtouch"
  ],
  "setCode": "aa3",
  "collectorNumber": "15",
  "commanderLegality": "legal",
  "singleImage": true
};

export const BALEFUL_STRIX: CardData = {
  "scryfallId": "06cb1bd6-73e0-4104-b344-4bc52d7dcedf",
  "oracleId": "37688720-03de-4eca-a82d-a0afe8d58adc",
  "name": "Baleful Strix",
  "layout": "normal",
  "faces": [
    {
      "name": "Baleful Strix",
      "manaCost": "{U}{B}",
      "typeLine": "Artifact Creature — Bird",
      "oracleText": "Flying, deathtouch\nWhen this creature enters, draw a card.",
      "flavorText": "Its beak rends flesh and bone, exposing the tender marrow of dream.",
      "power": "1",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "B",
        "U"
      ],
      "artist": "Nils Hamm",
      "imageId": "06cb1bd6-73e0-4104-b344-4bc52d7dcedf"
    }
  ],
  "colorIdentity": [
    "B",
    "U"
  ],
  "cmc": 2,
  "keywords": [
    "Deathtouch",
    "Flying"
  ],
  "setCode": "e01",
  "collectorNumber": "80",
  "commanderLegality": "legal",
  "singleImage": true
};

export const TARMOGOYF: CardData = {
  "scryfallId": "1cfdd410-391b-4b71-8139-f5a30653097a",
  "oracleId": "45900b2f-f6a9-4c42-9642-008f3c1cf6dd",
  "name": "Tarmogoyf",
  "layout": "normal",
  "faces": [
    {
      "name": "Tarmogoyf",
      "manaCost": "{1}{G}",
      "typeLine": "Creature — Lhurgoyf",
      "oracleText": "Tarmogoyf's power is equal to the number of card types among cards in all graveyards and its toughness is equal to that number plus 1.",
      "flavorText": "What doesn't grow, dies. And what dies grows the tarmogoyf.",
      "power": "*",
      "toughness": "1+*",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Ryan Barger",
      "imageId": "1cfdd410-391b-4b71-8139-f5a30653097a"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 2,
  "keywords": [],
  "setCode": "mm2",
  "collectorNumber": "165",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SPEARBREAKER_BEHEMOTH: CardData = {
  "scryfallId": "132367ee-22e9-48e2-82e0-62ad9aaa62f3",
  "oracleId": "025f8db8-11d1-4c59-8e1f-004c9c843fd8",
  "name": "Spearbreaker Behemoth",
  "layout": "normal",
  "faces": [
    {
      "name": "Spearbreaker Behemoth",
      "manaCost": "{5}{G}{G}",
      "typeLine": "Creature — Beast",
      "oracleText": "Indestructible\n{1}: Target creature with power 5 or greater gains indestructible until end of turn.",
      "flavorText": "Few Nayans dare hunt the gargantuans. They're regarded not as animals but as forces of nature, like landslides or typhoons.",
      "power": "5",
      "toughness": "5",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Christopher Moeller",
      "imageId": "132367ee-22e9-48e2-82e0-62ad9aaa62f3"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 7,
  "keywords": [
    "Indestructible"
  ],
  "setCode": "ala",
  "collectorNumber": "150",
  "commanderLegality": "legal",
  "singleImage": true
};

export const PRIESTS_OF_NORN: CardData = {
  "scryfallId": "07e7edbc-0d20-4d5f-8ab1-fdf642607bf2",
  "oracleId": "793fe31a-2b11-49f8-9851-719469ad1726",
  "name": "Priests of Norn",
  "layout": "normal",
  "faces": [
    {
      "name": "Priests of Norn",
      "manaCost": "{2}{W}",
      "typeLine": "Creature — Phyrexian Cleric",
      "oracleText": "Vigilance\nInfect (This creature deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.)",
      "flavorText": "\"May our blessings sever the tongues of the forsaken.\"\n—Elesh Norn, Grand Cenobite",
      "power": "1",
      "toughness": "4",
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Igor Kieryluk",
      "imageId": "07e7edbc-0d20-4d5f-8ab1-fdf642607bf2"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 3,
  "keywords": [
    "Vigilance",
    "Infect"
  ],
  "setCode": "plst",
  "collectorNumber": "MBS-16",
  "commanderLegality": "legal",
  "singleImage": true
};

export const ROT_WOLF: CardData = {
  "scryfallId": "0b08563c-1a00-4d9d-8e4f-13e4b9b0629f",
  "oracleId": "7409906d-7111-48fa-bfea-8b95e0fdb7dc",
  "name": "Rot Wolf",
  "layout": "normal",
  "faces": [
    {
      "name": "Rot Wolf",
      "manaCost": "{2}{G}",
      "typeLine": "Creature — Phyrexian Wolf",
      "oracleText": "Infect (This creature deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.)\nWhenever a creature dealt damage by Rot Wolf this turn dies, you may draw a card.",
      "flavorText": null,
      "power": "2",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Nils Hamm",
      "imageId": "0b08563c-1a00-4d9d-8e4f-13e4b9b0629f"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 3,
  "keywords": [
    "Infect"
  ],
  "setCode": "td2",
  "collectorNumber": "54",
  "commanderLegality": "legal",
  "singleImage": true
};

export const FLENSERMITE: CardData = {
  "scryfallId": "0017de60-ee1c-4675-b04e-cdfa2c2a596e",
  "oracleId": "4b63bf36-cd0e-41d8-b0ca-aac459d91f3f",
  "name": "Flensermite",
  "layout": "normal",
  "faces": [
    {
      "name": "Flensermite",
      "manaCost": "{1}{B}",
      "typeLine": "Creature — Phyrexian Gremlin",
      "oracleText": "Infect (This creature deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.)\nLifelink (Damage dealt by this creature also causes you to gain that much life.)",
      "flavorText": null,
      "power": "1",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "B"
      ],
      "artist": "Dave Allsop",
      "imageId": "0017de60-ee1c-4675-b04e-cdfa2c2a596e"
    }
  ],
  "colorIdentity": [
    "B"
  ],
  "cmc": 2,
  "keywords": [
    "Lifelink",
    "Infect"
  ],
  "setCode": "mbs",
  "collectorNumber": "41",
  "commanderLegality": "legal",
  "singleImage": true
};

export const TWINBLADE_SLASHER: CardData = {
  "scryfallId": "0092d7a0-bd00-45e5-a052-c0a9d970bc2e",
  "oracleId": "2375a9c6-28ef-4c8f-909c-0aa7e5fc085c",
  "name": "Twinblade Slasher",
  "layout": "normal",
  "faces": [
    {
      "name": "Twinblade Slasher",
      "manaCost": "{G}",
      "typeLine": "Creature — Elf Warrior",
      "oracleText": "Wither (This deals damage to creatures in the form of -1/-1 counters.)\n{1}{G}: This creature gets +2/+2 until end of turn. Activate only once each turn.",
      "flavorText": "Righteous anger hones a humble soul.",
      "power": "1",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Trevor Hairsine",
      "imageId": "0092d7a0-bd00-45e5-a052-c0a9d970bc2e"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 1,
  "keywords": [
    "Wither"
  ],
  "setCode": "eve",
  "collectorNumber": "79",
  "commanderLegality": "legal",
  "singleImage": true
};

export const TYRRANAX_REX: CardData = {
  "scryfallId": "0fb52b44-da5f-4f7a-a6c2-7924b855e051",
  "oracleId": "6e42da0c-151e-468d-91cb-5a5b117a9298",
  "name": "Tyrranax Rex",
  "layout": "normal",
  "faces": [
    {
      "name": "Tyrranax Rex",
      "manaCost": "{4}{G}{G}{G}",
      "typeLine": "Creature — Phyrexian Dinosaur",
      "oracleText": "This spell can't be countered.\nTrample, ward {4}, haste\nToxic 4 (Players dealt combat damage by this creature also get four poison counters.)",
      "flavorText": null,
      "power": "8",
      "toughness": "8",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Tuan Duong Chu",
      "imageId": "0fb52b44-da5f-4f7a-a6c2-7924b855e051"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 7,
  "keywords": [
    "Toxic",
    "Haste",
    "Trample",
    "Ward"
  ],
  "setCode": "one",
  "collectorNumber": "189",
  "commanderLegality": "legal",
  "singleImage": true
};

export const BLOATED_CONTAMINATOR: CardData = {
  "scryfallId": "131cbcca-f9a9-43cb-a0c8-c95e246f6237",
  "oracleId": "090018e0-4dcb-4b3c-b4e0-7ba62de0484d",
  "name": "Bloated Contaminator",
  "layout": "normal",
  "faces": [
    {
      "name": "Bloated Contaminator",
      "manaCost": "{2}{G}",
      "typeLine": "Creature — Phyrexian Beast",
      "oracleText": "Trample\nToxic 1 (Players dealt combat damage by this creature also get a poison counter.)\nWhenever this creature deals combat damage to a player, proliferate. (Choose any number of permanents and/or players, then give each another counter of each kind already there.)",
      "flavorText": null,
      "power": "4",
      "toughness": "4",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Johann Bodin",
      "imageId": "131cbcca-f9a9-43cb-a0c8-c95e246f6237"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 3,
  "keywords": [
    "Toxic",
    "Trample",
    "Proliferate"
  ],
  "setCode": "pone",
  "collectorNumber": "159p",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SEDGEMOOR_WITCH: CardData = {
  "scryfallId": "075bfaa8-3d54-4934-aaf6-72be43a87324",
  "oracleId": "25dce517-ac0a-4577-89ed-04296c7c4069",
  "name": "Sedgemoor Witch",
  "layout": "normal",
  "faces": [
    {
      "name": "Sedgemoor Witch",
      "manaCost": "{2}{B}",
      "typeLine": "Creature — Human Warlock",
      "oracleText": "Menace\nWard—Pay 3 life. (Whenever this creature becomes the target of a spell or ability an opponent controls, counter it unless that player pays 3 life.)\nMagecraft — Whenever you cast or copy an instant or sorcery spell, create a 1/1 black and green Pest creature token with \"When this token dies, you gain 1 life.\"",
      "flavorText": null,
      "power": "3",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "B"
      ],
      "artist": "Igor Kieryluk",
      "imageId": "075bfaa8-3d54-4934-aaf6-72be43a87324"
    }
  ],
  "colorIdentity": [
    "B"
  ],
  "cmc": 3,
  "keywords": [
    "Magecraft",
    "Menace",
    "Ward"
  ],
  "setCode": "stx",
  "collectorNumber": "306",
  "commanderLegality": "legal",
  "singleImage": true
};

export const DELVER_OF_SECRETS_INSECTILE_ABERRATION: CardData = {
  "scryfallId": "11bf83bb-c95b-4b4f-9a56-ce7a1816307a",
  "oracleId": "edd531b9-f615-4399-8c8c-1c5e18c4acbf",
  "name": "Delver of Secrets // Insectile Aberration",
  "layout": "transform",
  "faces": [
    {
      "name": "Delver of Secrets",
      "manaCost": "{U}",
      "typeLine": "Creature — Human Wizard",
      "oracleText": "At the beginning of your upkeep, look at the top card of your library. You may reveal that card. If an instant or sorcery card is revealed this way, transform this creature.",
      "flavorText": null,
      "power": "1",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "U"
      ],
      "artist": "Nils Hamm",
      "imageId": "11bf83bb-c95b-4b4f-9a56-ce7a1816307a-0"
    },
    {
      "name": "Insectile Aberration",
      "manaCost": "",
      "typeLine": "Creature — Human Insect",
      "oracleText": "Flying",
      "flavorText": "\"Unfortunately, all my test animals have died or escaped, so I shall be the final subject. I feel no fear. This is a momentous night.\"\n—Laboratory notes, final entry",
      "power": "3",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "U"
      ],
      "artist": "Nils Hamm",
      "imageId": "11bf83bb-c95b-4b4f-9a56-ce7a1816307a-1"
    }
  ],
  "colorIdentity": [
    "U"
  ],
  "cmc": 1,
  "keywords": [
    "Flying",
    "Transform"
  ],
  "setCode": "isd",
  "collectorNumber": "51",
  "commanderLegality": "legal",
  "singleImage": false
};

export const FIGURE_OF_DESTINY: CardData = {
  "scryfallId": "0da69523-cece-425a-b08a-fb27fac29374",
  "oracleId": "cd51cc2d-0d39-4aba-b0ea-70e8118149bc",
  "name": "Figure of Destiny",
  "layout": "normal",
  "faces": [
    {
      "name": "Figure of Destiny",
      "manaCost": "{R/W}",
      "typeLine": "Creature — Kithkin",
      "oracleText": "{R/W}: This creature becomes a Kithkin Spirit with base power and toughness 2/2.\n{R/W}{R/W}{R/W}: If this creature is a Spirit, it becomes a Kithkin Spirit Warrior with base power and toughness 4/4.\n{R/W}{R/W}{R/W}{R/W}{R/W}{R/W}: If this creature is a Warrior, it becomes a Kithkin Spirit Warrior Avatar with base power and toughness 8/8, flying, and first strike.",
      "flavorText": null,
      "power": "1",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "R",
        "W"
      ],
      "artist": "Scott M. Fischer",
      "imageId": "0da69523-cece-425a-b08a-fb27fac29374"
    }
  ],
  "colorIdentity": [
    "R",
    "W"
  ],
  "cmc": 1,
  "keywords": [],
  "setCode": "eve",
  "collectorNumber": "139",
  "commanderLegality": "legal",
  "singleImage": true
};

export const GITAXIAN_PROBE: CardData = {
  "scryfallId": "1fbb4493-23db-4c91-a3e0-17b139f5d00f",
  "oracleId": "1d67f5ff-1fce-45e5-b6a1-416c569351e2",
  "name": "Gitaxian Probe",
  "layout": "normal",
  "faces": [
    {
      "name": "Gitaxian Probe",
      "manaCost": "{U/P}",
      "typeLine": "Sorcery",
      "oracleText": "({U/P} can be paid with either {U} or 2 life.)\nLook at target player's hand.\nDraw a card.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "U"
      ],
      "artist": "Pedro Correa",
      "imageId": "1fbb4493-23db-4c91-a3e0-17b139f5d00f"
    }
  ],
  "colorIdentity": [
    "U"
  ],
  "cmc": 1,
  "keywords": [],
  "setCode": "sld",
  "collectorNumber": "2067",
  "commanderLegality": "legal",
  "singleImage": true
};

export const FIRE_ICE: CardData = {
  "scryfallId": "04cb4e4e-8275-4132-8f1a-84b486725400",
  "oracleId": "ae92942b-919c-4ea9-b693-85fcef765d5a",
  "name": "Fire // Ice",
  "layout": "split",
  "faces": [
    {
      "name": "Fire",
      "manaCost": "{1}{R}",
      "typeLine": "Instant",
      "oracleText": "Fire deals 2 damage divided as you choose among one or two targets.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "David Martin",
      "imageId": "04cb4e4e-8275-4132-8f1a-84b486725400"
    },
    {
      "name": "Ice",
      "manaCost": "{1}{U}",
      "typeLine": "Instant",
      "oracleText": "Tap target permanent.\nDraw a card.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Franz Vohwinkel",
      "imageId": "04cb4e4e-8275-4132-8f1a-84b486725400"
    }
  ],
  "colorIdentity": [
    "R",
    "U"
  ],
  "cmc": 4,
  "keywords": [],
  "setCode": "f06",
  "collectorNumber": "12a",
  "commanderLegality": "legal",
  "singleImage": true
};

export const WEAR_TEAR: CardData = {
  "scryfallId": "0f279560-7e9f-4a6d-9fd6-6c8c6bd94a1b",
  "oracleId": "9842734c-1eac-4509-a731-4c22017ae586",
  "name": "Wear // Tear",
  "layout": "split",
  "faces": [
    {
      "name": "Wear",
      "manaCost": "{1}{R}",
      "typeLine": "Instant",
      "oracleText": "Destroy target artifact.\nFuse (You may cast one or both halves of this card from your hand.)",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Ryan Pancoast",
      "imageId": "0f279560-7e9f-4a6d-9fd6-6c8c6bd94a1b"
    },
    {
      "name": "Tear",
      "manaCost": "{W}",
      "typeLine": "Instant",
      "oracleText": "Destroy target enchantment.\nFuse (You may cast one or both halves of this card from your hand.)",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Ryan Pancoast",
      "imageId": "0f279560-7e9f-4a6d-9fd6-6c8c6bd94a1b"
    }
  ],
  "colorIdentity": [
    "R",
    "W"
  ],
  "cmc": 3,
  "keywords": [
    "Fuse"
  ],
  "setCode": "cmr",
  "collectorNumber": "456",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SHORIKAI_GENESIS_ENGINE: CardData = {
  "scryfallId": "0347cf84-42f5-4674-99de-619b0ae51d62",
  "oracleId": "e2962883-6daf-4a84-af73-917afc73092c",
  "name": "Shorikai, Genesis Engine",
  "layout": "normal",
  "faces": [
    {
      "name": "Shorikai, Genesis Engine",
      "manaCost": "{2}{W}{U}",
      "typeLine": "Legendary Artifact — Vehicle",
      "oracleText": "{1}, {T}: Draw two cards, then discard a card. Create a 1/1 colorless Pilot creature token with \"This token crews Vehicles as though its power were 2 greater.\"\nCrew 8 (Tap any number of creatures you control with total power 8 or more: This Vehicle becomes an artifact creature until end of turn.)",
      "flavorText": null,
      "power": "8",
      "toughness": "8",
      "loyalty": null,
      "defense": null,
      "colors": [
        "U",
        "W"
      ],
      "artist": "Wisnu Tan",
      "imageId": "0347cf84-42f5-4674-99de-619b0ae51d62"
    }
  ],
  "colorIdentity": [
    "U",
    "W"
  ],
  "cmc": 4,
  "keywords": [
    "Crew"
  ],
  "setCode": "nec",
  "collectorNumber": "76",
  "commanderLegality": "legal",
  "singleImage": true
};

export const LIGHTNING_BOLT: CardData = {
  "scryfallId": "0277c0b1-da97-49c1-a539-7fbaa1f77419",
  "oracleId": "4457ed35-7c10-48c8-9776-456485fdf070",
  "name": "Lightning Bolt",
  "layout": "normal",
  "faces": [
    {
      "name": "Lightning Bolt",
      "manaCost": "{R}",
      "typeLine": "Instant",
      "oracleText": "Lightning Bolt deals 3 damage to any target.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "R"
      ],
      "artist": "Christopher Rush",
      "imageId": "0277c0b1-da97-49c1-a539-7fbaa1f77419"
    }
  ],
  "colorIdentity": [
    "R"
  ],
  "cmc": 1,
  "keywords": [],
  "setCode": "sld",
  "collectorNumber": "901",
  "commanderLegality": "legal",
  "singleImage": true
};

export const COUNTERSPELL: CardData = {
  "scryfallId": "02da8709-4228-4fed-9d2d-781e686661df",
  "oracleId": "cc187110-1148-4090-bbb8-e205694a39f5",
  "name": "Counterspell",
  "layout": "normal",
  "faces": [
    {
      "name": "Counterspell",
      "manaCost": "{U}{U}",
      "typeLine": "Instant",
      "oracleText": "Counter target spell.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "U"
      ],
      "artist": "Zack Stella",
      "imageId": "02da8709-4228-4fed-9d2d-781e686661df"
    }
  ],
  "colorIdentity": [
    "U"
  ],
  "cmc": 2,
  "keywords": [],
  "setCode": "dmr",
  "collectorNumber": "45",
  "commanderLegality": "legal",
  "singleImage": true
};

export const CULTIVATE: CardData = {
  "scryfallId": "075cac04-9397-4edb-b49a-485dd58dcae1",
  "oracleId": "8b755881-a72d-4e21-a369-d2924eb4585a",
  "name": "Cultivate",
  "layout": "normal",
  "faces": [
    {
      "name": "Cultivate",
      "manaCost": "{2}{G}",
      "typeLine": "Sorcery",
      "oracleText": "Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle.",
      "flavorText": "All seeds share a common bond, calling to each other across infinity.",
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Anthony Palumbo",
      "imageId": "075cac04-9397-4edb-b49a-485dd58dcae1"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 3,
  "keywords": [],
  "setCode": "j22",
  "collectorNumber": "644",
  "commanderLegality": "legal",
  "singleImage": true
};

export const SWORDS_TO_PLOWSHARES: CardData = {
  "scryfallId": "04e0738b-b856-401e-8b41-096e2c48cf96",
  "oracleId": "b1544f21-7e98-461b-aed5-e748b0168c52",
  "name": "Swords to Plowshares",
  "layout": "normal",
  "faces": [
    {
      "name": "Swords to Plowshares",
      "manaCost": "{W}",
      "typeLine": "Instant",
      "oracleText": "Exile target creature. Its controller gains life equal to its power.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Jeff A. Menges",
      "imageId": "04e0738b-b856-401e-8b41-096e2c48cf96"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 1,
  "keywords": [],
  "setCode": "ptc",
  "collectorNumber": "ml52",
  "commanderLegality": "legal",
  "singleImage": true
};

export const PACIFISM: CardData = {
  "scryfallId": "0bec2191-7478-4bf8-97d4-b8204990b5d7",
  "oracleId": "5f5e0b10-c8cf-450c-bfd3-bcb0528ec330",
  "name": "Pacifism",
  "layout": "normal",
  "faces": [
    {
      "name": "Pacifism",
      "manaCost": "{1}{W}",
      "typeLine": "Enchantment — Aura",
      "oracleText": "Enchant creature\nEnchanted creature can't attack or block.",
      "flavorText": "For the first time in his life, Grakk felt a little warm and fuzzy inside.",
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Robert Bliss",
      "imageId": "0bec2191-7478-4bf8-97d4-b8204990b5d7"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 2,
  "keywords": [
    "Enchant"
  ],
  "setCode": "wc04",
  "collectorNumber": "gn33sb",
  "commanderLegality": "legal",
  "singleImage": true
};

export const WRATH_OF_GOD: CardData = {
  "scryfallId": "0619d670-7b53-4185-a25d-2fab5db1aab5",
  "oracleId": "34515b16-c9a4-4f98-8c77-416a7a523407",
  "name": "Wrath of God",
  "layout": "normal",
  "faces": [
    {
      "name": "Wrath of God",
      "manaCost": "{2}{W}{W}",
      "typeLine": "Sorcery",
      "oracleText": "Destroy all creatures. They can't be regenerated.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Kev Walker",
      "imageId": "0619d670-7b53-4185-a25d-2fab5db1aab5"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 4,
  "keywords": [],
  "setCode": "8ed",
  "collectorNumber": "58",
  "commanderLegality": "legal",
  "singleImage": true
};

export const BRAINSTORM: CardData = {
  "scryfallId": "02af4960-b013-4a86-9dd3-8f0c3e419c84",
  "oracleId": "36cd2364-d113-47d1-b2c4-b088d9eb88dd",
  "name": "Brainstorm",
  "layout": "normal",
  "faces": [
    {
      "name": "Brainstorm",
      "manaCost": "{U}",
      "typeLine": "Instant",
      "oracleText": "Draw three cards, then put two cards from your hand on top of your library in any order.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "U"
      ],
      "artist": "Ron Spencer",
      "imageId": "02af4960-b013-4a86-9dd3-8f0c3e419c84"
    }
  ],
  "colorIdentity": [
    "U"
  ],
  "cmc": 1,
  "keywords": [],
  "setCode": "prm",
  "collectorNumber": "82834",
  "commanderLegality": "legal",
  "singleImage": true
};

export const DARK_RITUAL: CardData = {
  "scryfallId": "0690f724-eb95-416b-b064-f1239e2a30e8",
  "oracleId": "53f7c868-b03e-4fc2-8dcf-a75bbfa3272b",
  "name": "Dark Ritual",
  "layout": "normal",
  "faces": [
    {
      "name": "Dark Ritual",
      "manaCost": "{B}",
      "typeLine": "Instant",
      "oracleText": "Add {B}{B}{B}.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "B"
      ],
      "artist": "Sandra Everingham",
      "imageId": "0690f724-eb95-416b-b064-f1239e2a30e8"
    }
  ],
  "colorIdentity": [
    "B"
  ],
  "cmc": 1,
  "keywords": [],
  "setCode": "leb",
  "collectorNumber": "99",
  "commanderLegality": "legal",
  "singleImage": true
};

export const KESS_DISSIDENT_MAGE: CardData = {
  "scryfallId": "01711ff6-475c-48c4-91f4-438433f88a95",
  "oracleId": "f5092c14-eec4-472c-999c-ba96c36b2fbb",
  "name": "Kess, Dissident Mage",
  "layout": "normal",
  "faces": [
    {
      "name": "Kess, Dissident Mage",
      "manaCost": "{1}{U}{B}{R}",
      "typeLine": "Legendary Creature — Human Wizard",
      "oracleText": "Flying\nOnce during each of your turns, you may cast an instant or sorcery spell from your graveyard. If a spell cast this way would be put into your graveyard, exile it instead.",
      "flavorText": "\"Loss has no meaning here. You cannot take from those who have nothing.\"",
      "power": "3",
      "toughness": "4",
      "loyalty": null,
      "defense": null,
      "colors": [
        "B",
        "R",
        "U"
      ],
      "artist": "Izzy",
      "imageId": "01711ff6-475c-48c4-91f4-438433f88a95"
    }
  ],
  "colorIdentity": [
    "B",
    "R",
    "U"
  ],
  "cmc": 4,
  "keywords": [
    "Flying"
  ],
  "setCode": "c17",
  "collectorNumber": "39",
  "commanderLegality": "legal",
  "singleImage": true
};

export const KRENKO_MOB_BOSS: CardData = {
  "scryfallId": "0b9c68ff-1fe4-42ef-8d1f-43120de5c1ff",
  "oracleId": "68418069-f615-40ef-ae0d-764192acae00",
  "name": "Krenko, Mob Boss",
  "layout": "normal",
  "faces": [
    {
      "name": "Krenko, Mob Boss",
      "manaCost": "{2}{R}{R}",
      "typeLine": "Legendary Creature — Goblin Warrior",
      "oracleText": "{T}: Create X 1/1 red Goblin creature tokens, where X is the number of Goblins you control.",
      "flavorText": "\"He displays a perverse charisma fueled by avarice. Highly dangerous. Recommend civil sanctions.\"\n—Agmand Sarv, Azorius hussar",
      "power": "3",
      "toughness": "3",
      "loyalty": null,
      "defense": null,
      "colors": [
        "R"
      ],
      "artist": "Karl Kopinski",
      "imageId": "0b9c68ff-1fe4-42ef-8d1f-43120de5c1ff"
    }
  ],
  "colorIdentity": [
    "R"
  ],
  "cmc": 4,
  "keywords": [],
  "setCode": "j22",
  "collectorNumber": "564",
  "commanderLegality": "legal",
  "singleImage": true
};

export const TALRAND_SKY_SUMMONER: CardData = {
  "scryfallId": "0ea31d56-3530-41b4-8d31-c6ee16e87ae6",
  "oracleId": "ea1eb902-a23c-44ff-9169-19baf71de238",
  "name": "Talrand, Sky Summoner",
  "layout": "normal",
  "faces": [
    {
      "name": "Talrand, Sky Summoner",
      "manaCost": "{2}{U}{U}",
      "typeLine": "Legendary Creature — Merfolk Wizard",
      "oracleText": "Whenever you cast an instant or sorcery spell, create a 2/2 blue Drake creature token with flying.",
      "flavorText": "\"The seas are vast, but the skies are even more so. Why be content with one kingdom when I can rule them both?\"",
      "power": "2",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "U"
      ],
      "artist": "Svetlin Velinov",
      "imageId": "0ea31d56-3530-41b4-8d31-c6ee16e87ae6"
    }
  ],
  "colorIdentity": [
    "U"
  ],
  "cmc": 4,
  "keywords": [],
  "setCode": "plst",
  "collectorNumber": "DDS-11",
  "commanderLegality": "legal",
  "singleImage": true
};

export const YEVA_NATURE_S_HERALD: CardData = {
  "scryfallId": "13c45f04-b844-4219-b7c5-5fd42edacc78",
  "oracleId": "2d513c3e-bd27-479e-af32-7f66d96d0de0",
  "name": "Yeva, Nature's Herald",
  "layout": "normal",
  "faces": [
    {
      "name": "Yeva, Nature's Herald",
      "manaCost": "{2}{G}{G}",
      "typeLine": "Legendary Creature — Elf Shaman",
      "oracleText": "Flash (You may cast this spell any time you could cast an instant.)\nYou may cast green creature spells as though they had flash.",
      "flavorText": "Their favorite place in all of Ravnica was still the glade where they first met.",
      "power": "4",
      "toughness": "4",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Aya Kakeda",
      "imageId": "13c45f04-b844-4219-b7c5-5fd42edacc78"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 4,
  "keywords": [
    "Flash"
  ],
  "setCode": "sld",
  "collectorNumber": "1284",
  "commanderLegality": "legal",
  "singleImage": true
};

export const THRASIOS_TRITON_HERO: CardData = {
  "scryfallId": "18d51c53-d45f-4df4-abf5-dfa3ba07c68c",
  "oracleId": "3d867016-2601-4a37-a73d-308898d3bd37",
  "name": "Thrasios, Triton Hero",
  "layout": "normal",
  "faces": [
    {
      "name": "Thrasios, Triton Hero",
      "manaCost": "{G}{U}",
      "typeLine": "Legendary Creature — Merfolk Wizard",
      "oracleText": "{4}: Scry 1, then reveal the top card of your library. If it's a land card, put it onto the battlefield tapped. Otherwise, draw a card.\nPartner (You can have two commanders if both have partner.)",
      "flavorText": null,
      "power": "1",
      "toughness": "3",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G",
        "U"
      ],
      "artist": "Josu Hernaiz",
      "imageId": "18d51c53-d45f-4df4-abf5-dfa3ba07c68c"
    }
  ],
  "colorIdentity": [
    "G",
    "U"
  ],
  "cmc": 2,
  "keywords": [
    "Partner",
    "Scry"
  ],
  "setCode": "prm",
  "collectorNumber": "86178",
  "commanderLegality": "legal",
  "singleImage": true
};

export const TYMNA_THE_WEAVER: CardData = {
  "scryfallId": "508b438b-bd85-4675-875e-af133d32da2c",
  "oracleId": "d15642e4-e61c-4d29-af48-de837991245e",
  "name": "Tymna the Weaver",
  "layout": "normal",
  "faces": [
    {
      "name": "Tymna the Weaver",
      "manaCost": "{1}{W}{B}",
      "typeLine": "Legendary Creature — Human Cleric",
      "oracleText": "Lifelink\nAt the beginning of each of your postcombat main phases, you may pay X life, where X is the number of opponents that were dealt combat damage this turn. If you do, draw X cards.\nPartner (You can have two commanders if both have partner.)",
      "flavorText": null,
      "power": "2",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "B",
        "W"
      ],
      "artist": "Winona Nelson",
      "imageId": "508b438b-bd85-4675-875e-af133d32da2c"
    }
  ],
  "colorIdentity": [
    "B",
    "W"
  ],
  "cmc": 3,
  "keywords": [
    "Lifelink",
    "Partner"
  ],
  "setCode": "prm",
  "collectorNumber": "86180",
  "commanderLegality": "legal",
  "singleImage": true
};

export const GRIST_THE_HUNGER_TIDE: CardData = {
  "scryfallId": "1925dc45-4dee-4772-aa16-3b4ca54be6c7",
  "oracleId": "0efb0d7e-dea0-4817-a243-15066e9ef333",
  "name": "Grist, the Hunger Tide",
  "layout": "normal",
  "faces": [
    {
      "name": "Grist, the Hunger Tide",
      "manaCost": "{1}{B}{G}",
      "typeLine": "Legendary Planeswalker — Grist",
      "oracleText": "As long as Grist isn't on the battlefield, it's a 1/1 Insect creature in addition to its other types.\n+1: Create a 1/1 black and green Insect creature token, then mill a card. If an Insect card was milled this way, put a loyalty counter on Grist and repeat this process.\n−2: You may sacrifice a creature. When you do, destroy target creature or planeswalker.\n−5: Each opponent loses life equal to the number of creature cards in your graveyard.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": "3",
      "defense": null,
      "colors": [
        "B",
        "G"
      ],
      "artist": "Yongjae Choi",
      "imageId": "1925dc45-4dee-4772-aa16-3b4ca54be6c7"
    }
  ],
  "colorIdentity": [
    "B",
    "G"
  ],
  "cmc": 3,
  "keywords": [
    "Mill"
  ],
  "setCode": "dsc",
  "collectorNumber": "220",
  "commanderLegality": "legal",
  "singleImage": true
};

export const AVACYN_ANGEL_OF_HOPE: CardData = {
  "scryfallId": "317f1133-7cf8-4b7a-919e-88c45f8c2c3a",
  "oracleId": "216cb26e-8da9-478b-bfbc-8030f7adee72",
  "name": "Avacyn, Angel of Hope",
  "layout": "normal",
  "faces": [
    {
      "name": "Avacyn, Angel of Hope",
      "manaCost": "{5}{W}{W}{W}",
      "typeLine": "Legendary Creature — Angel",
      "oracleText": "Flying, vigilance, indestructible\nOther permanents you control have indestructible.",
      "flavorText": "A golden helix streaked skyward from the Helvault. A thunderous explosion shattered the silver monolith and Avacyn emerged, free from her prison at last.",
      "power": "8",
      "toughness": "8",
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Jason Chan",
      "imageId": "317f1133-7cf8-4b7a-919e-88c45f8c2c3a"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 8,
  "keywords": [
    "Flying",
    "Indestructible",
    "Vigilance"
  ],
  "setCode": "cmm",
  "collectorNumber": "14",
  "commanderLegality": "legal",
  "singleImage": true
};

export const INVASION_OF_GOBAKHAN_LIGHTSHIELD_ARRAY: CardData = {
  "scryfallId": "11798730-6788-4e0b-a828-b46cab1a4fa7",
  "oracleId": "86c32a56-3272-4738-b0b3-a8aa49a17ce4",
  "name": "Invasion of Gobakhan // Lightshield Array",
  "layout": "transform",
  "faces": [
    {
      "name": "Invasion of Gobakhan",
      "manaCost": "{1}{W}",
      "typeLine": "Battle — Siege",
      "oracleText": "(As a Siege enters, choose an opponent to protect it. You and others can attack it. When it's defeated, exile it, then cast it transformed.)\nWhen this Siege enters, look at target opponent's hand. You may exile a nonland card from it. For as long as that card remains exiled, its owner may play it. A spell cast this way costs {2} more to cast.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": "3",
      "colors": [
        "W"
      ],
      "artist": "Andreas Zafiratos",
      "imageId": "11798730-6788-4e0b-a828-b46cab1a4fa7-0"
    },
    {
      "name": "Lightshield Array",
      "manaCost": "",
      "typeLine": "Enchantment",
      "oracleText": "At the beginning of your end step, put a +1/+1 counter on each creature that attacked this turn.\nSacrifice this enchantment: Creatures you control gain hexproof and indestructible until end of turn.",
      "flavorText": "The weight of Phyrexia crashed down upon Gobakhan, but the will of its people endured.",
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Andreas Zafiratos",
      "imageId": "11798730-6788-4e0b-a828-b46cab1a4fa7-1"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 2,
  "keywords": [
    "Transform"
  ],
  "setCode": "mom",
  "collectorNumber": "22",
  "commanderLegality": "legal",
  "singleImage": false
};

export const JACE_VRYN_S_PRODIGY_JACE_TELEPATH_UNBOUND: CardData = {
  "scryfallId": "02d6d693-f1f3-4317-bcc0-c21fa8490d38",
  "oracleId": "594f6881-c059-46f8-aa4e-7151d502de73",
  "name": "Jace, Vryn's Prodigy // Jace, Telepath Unbound",
  "layout": "transform",
  "faces": [
    {
      "name": "Jace, Vryn's Prodigy",
      "manaCost": "{1}{U}",
      "typeLine": "Legendary Creature — Human Wizard",
      "oracleText": "{T}: Draw a card, then discard a card. If there are five or more cards in your graveyard, exile Jace, then return him to the battlefield transformed under his owner's control.",
      "flavorText": "\"People's thoughts just come to me. Sometimes I don't know if it's them or me thinking.\"",
      "power": "0",
      "toughness": "2",
      "loyalty": null,
      "defense": null,
      "colors": [
        "U"
      ],
      "artist": "Jaime Jones",
      "imageId": "02d6d693-f1f3-4317-bcc0-c21fa8490d38-0"
    },
    {
      "name": "Jace, Telepath Unbound",
      "manaCost": "",
      "typeLine": "Legendary Planeswalker — Jace",
      "oracleText": "+1: Up to one target creature gets -2/-0 until your next turn.\n−3: You may cast target instant or sorcery card from your graveyard this turn. If that spell would be put into your graveyard, exile it instead.\n−9: You get an emblem with \"Whenever you cast a spell, target opponent mills five cards.\"",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": "5",
      "defense": null,
      "colors": [
        "U"
      ],
      "artist": "Jaime Jones",
      "imageId": "02d6d693-f1f3-4317-bcc0-c21fa8490d38-1"
    }
  ],
  "colorIdentity": [
    "U"
  ],
  "cmc": 2,
  "keywords": [
    "Transform",
    "Mill"
  ],
  "setCode": "ori",
  "collectorNumber": "60",
  "commanderLegality": "legal",
  "singleImage": false
};

export const ARLINN_KORD_ARLINN_EMBRACED_BY_THE_MOON: CardData = {
  "scryfallId": "314c478c-cd8e-4256-9542-79846c6f8f63",
  "oracleId": "6bb7d0df-7a9f-4e17-8c31-7628c4b12356",
  "name": "Arlinn Kord // Arlinn, Embraced by the Moon",
  "layout": "transform",
  "faces": [
    {
      "name": "Arlinn Kord",
      "manaCost": "{2}{R}{G}",
      "typeLine": "Legendary Planeswalker — Arlinn",
      "oracleText": "+1: Until end of turn, up to one target creature gets +2/+2 and gains vigilance and haste.\n0: Create a 2/2 green Wolf creature token. Transform Arlinn Kord.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": "3",
      "defense": null,
      "colors": [
        "G",
        "R"
      ],
      "artist": "Winona Nelson",
      "imageId": "314c478c-cd8e-4256-9542-79846c6f8f63-0"
    },
    {
      "name": "Arlinn, Embraced by the Moon",
      "manaCost": "",
      "typeLine": "Legendary Planeswalker — Arlinn",
      "oracleText": "+1: Creatures you control get +1/+1 and gain trample until end of turn.\n−1: Arlinn deals 3 damage to any target. Transform Arlinn.\n−6: You get an emblem with \"Creatures you control have haste and '{T}: This creature deals damage equal to its power to any target.'\"",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [
        "G",
        "R"
      ],
      "artist": "Winona Nelson",
      "imageId": "314c478c-cd8e-4256-9542-79846c6f8f63-1"
    }
  ],
  "colorIdentity": [
    "G",
    "R"
  ],
  "cmc": 4,
  "keywords": [
    "Transform"
  ],
  "setCode": "plst",
  "collectorNumber": "SOI-243",
  "commanderLegality": "legal",
  "singleImage": false
};

export const INVASION_OF_NEW_PHYREXIA_TEFERI_AKOSA_OF_ZHALFIR: CardData = {
  "scryfallId": "1b83af86-e1a9-4be1-83dc-0c1ab81b129e",
  "oracleId": "480ea052-87d7-4fea-ac97-b6121b78f863",
  "name": "Invasion of New Phyrexia // Teferi Akosa of Zhalfir",
  "layout": "transform",
  "faces": [
    {
      "name": "Invasion of New Phyrexia",
      "manaCost": "{X}{W}{U}",
      "typeLine": "Battle — Siege",
      "oracleText": "(As a Siege enters, choose an opponent to protect it. You and others can attack it. When it's defeated, exile it, then cast it transformed.)\nWhen this Siege enters, create X 2/2 white and blue Knight creature tokens with vigilance.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": "6",
      "colors": [
        "U",
        "W"
      ],
      "artist": "Chris Rallis",
      "imageId": "1b83af86-e1a9-4be1-83dc-0c1ab81b129e-0"
    },
    {
      "name": "Teferi Akosa of Zhalfir",
      "manaCost": "",
      "typeLine": "Legendary Planeswalker — Teferi",
      "oracleText": "+1: Draw two cards. Then discard two cards unless you discard a creature card.\n−2: You get an emblem with \"Knights you control get +1/+0 and have ward {1}.\"\n−3: Tap any number of untapped creatures you control. When you do, shuffle target nonland permanent an opponent controls with mana value X or less into its owner's library, where X is the number of creatures tapped this way.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": "4",
      "defense": null,
      "colors": [
        "U",
        "W"
      ],
      "artist": "Chris Rallis",
      "imageId": "1b83af86-e1a9-4be1-83dc-0c1ab81b129e-1"
    }
  ],
  "colorIdentity": [
    "U",
    "W"
  ],
  "cmc": 2,
  "keywords": [
    "Transform"
  ],
  "setCode": "mom",
  "collectorNumber": "239",
  "commanderLegality": "legal",
  "singleImage": false
};

export const SOLDIER_TOKEN: CardData = {
  "scryfallId": "05e8f775-02bd-46dc-a618-07a9a127fa69",
  "oracleId": "eac25f12-6459-438c-a09e-93e23d2cf80d",
  "name": "Soldier",
  "layout": "token",
  "faces": [
    {
      "name": "Soldier",
      "manaCost": "",
      "typeLine": "Token Creature — Soldier",
      "oracleText": "",
      "flavorText": null,
      "power": "1",
      "toughness": "1",
      "loyalty": null,
      "defense": null,
      "colors": [
        "W"
      ],
      "artist": "Goran Josic",
      "imageId": "05e8f775-02bd-46dc-a618-07a9a127fa69"
    }
  ],
  "colorIdentity": [
    "W"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "tmd1",
  "collectorNumber": "1",
  "commanderLegality": "not_legal",
  "singleImage": true
};

export const TREASURE_TOKEN: CardData = {
  "scryfallId": "0559f9f3-eff0-465d-93c1-e875a8afe87f",
  "oracleId": "3c549374-6c37-42e0-8d88-a8555d46732d",
  "name": "Treasure",
  "layout": "token",
  "faces": [
    {
      "name": "Treasure",
      "manaCost": "",
      "typeLine": "Token Artifact — Treasure",
      "oracleText": "{T}, Sacrifice this token: Add one mana of any color.",
      "flavorText": null,
      "power": null,
      "toughness": null,
      "loyalty": null,
      "defense": null,
      "colors": [],
      "artist": "Mark Behm",
      "imageId": "0559f9f3-eff0-465d-93c1-e875a8afe87f"
    }
  ],
  "colorIdentity": [],
  "cmc": 0,
  "keywords": [],
  "setCode": "trna",
  "collectorNumber": "12",
  "commanderLegality": "not_legal",
  "singleImage": true
};

export const BEAST_TOKEN: CardData = {
  "scryfallId": "01e095bd-091c-442f-aa21-0826c40acb6c",
  "oracleId": "6bb61f34-5d57-4eaa-a02c-f5d08c1ee920",
  "name": "Beast",
  "layout": "token",
  "faces": [
    {
      "name": "Beast",
      "manaCost": "",
      "typeLine": "Token Creature — Beast",
      "oracleText": "",
      "flavorText": null,
      "power": "3",
      "toughness": "3",
      "loyalty": null,
      "defense": null,
      "colors": [
        "G"
      ],
      "artist": "Jesper Ejsing",
      "imageId": "01e095bd-091c-442f-aa21-0826c40acb6c"
    }
  ],
  "colorIdentity": [
    "G"
  ],
  "cmc": 0,
  "keywords": [],
  "setCode": "tclb",
  "collectorNumber": "38",
  "commanderLegality": "not_legal",
  "singleImage": true
};

/** Every fixture card, for building an OracleDb in a test. */
export const ENGINE_CARDS: CardData[] = [
  PLAINS,
  ISLAND,
  SWAMP,
  MOUNTAIN,
  FOREST,
  WASTES,
  SNOW_COVERED_FOREST,
  COMMAND_TOWER,
  TUNDRA,
  ANCIENT_TOMB,
  BOROS_GARRISON,
  GEMSTONE_MINE,
  REFLECTING_POOL,
  CAVERN_OF_SOULS,
  BOJUKA_BOG,
  SOL_RING,
  ARCANE_SIGNET,
  MOX_DIAMOND,
  LIGHTNING_GREAVES,
  DARKSTEEL_MYR,
  LLANOWAR_ELVES,
  BIRDS_OF_PARADISE,
  BLOOM_TENDER,
  GRIZZLY_BEARS,
  SCATHE_ZOMBIES,
  SILVERCOAT_LION,
  AIR_ELEMENTAL,
  SERRA_ANGEL,
  GIANT_SPIDER,
  COLOSSAL_DREADMAW,
  VAMPIRE_NIGHTHAWK,
  TYPHOID_RATS,
  WHITE_KNIGHT,
  BOROS_SWIFTBLADE,
  BOGGART_BRUTE,
  WALL_OF_OMENS,
  SCALED_BEHEMOTH,
  KOR_FIREWALKER,
  RAGING_GOBLIN,
  CHILD_OF_NIGHT,
  BULL_HIPPO,
  AMBUSH_VIPER,
  BALEFUL_STRIX,
  TARMOGOYF,
  SPEARBREAKER_BEHEMOTH,
  PRIESTS_OF_NORN,
  ROT_WOLF,
  FLENSERMITE,
  TWINBLADE_SLASHER,
  TYRRANAX_REX,
  BLOATED_CONTAMINATOR,
  SEDGEMOOR_WITCH,
  DELVER_OF_SECRETS_INSECTILE_ABERRATION,
  FIGURE_OF_DESTINY,
  GITAXIAN_PROBE,
  FIRE_ICE,
  WEAR_TEAR,
  SHORIKAI_GENESIS_ENGINE,
  LIGHTNING_BOLT,
  COUNTERSPELL,
  CULTIVATE,
  SWORDS_TO_PLOWSHARES,
  PACIFISM,
  WRATH_OF_GOD,
  BRAINSTORM,
  DARK_RITUAL,
  KESS_DISSIDENT_MAGE,
  KRENKO_MOB_BOSS,
  TALRAND_SKY_SUMMONER,
  YEVA_NATURE_S_HERALD,
  THRASIOS_TRITON_HERO,
  TYMNA_THE_WEAVER,
  GRIST_THE_HUNGER_TIDE,
  AVACYN_ANGEL_OF_HOPE,
  INVASION_OF_GOBAKHAN_LIGHTSHIELD_ARRAY,
  JACE_VRYN_S_PRODIGY_JACE_TELEPATH_UNBOUND,
  ARLINN_KORD_ARLINN_EMBRACED_BY_THE_MOON,
  INVASION_OF_NEW_PHYREXIA_TEFERI_AKOSA_OF_ZHALFIR,
  SOLDIER_TOKEN,
  TREASURE_TOKEN,
  BEAST_TOKEN,
];
