// GENERATED by src/data/botPool.node.test.ts — DO NOT EDIT BY HAND.
//
// Regenerate:  CRT_WRITE_BOT_DECK=1 npx vitest run src/data/botPool.node.test.ts
//
// The deck a bot seat plays. Every card in it is one the engine runs COMPLETELY
// — see `engineComplete.ts` — because a bot cannot read a card and apply it by
// hand the way a human can, so a card the app only partly runs is a card the bot
// must never draw.
//
// ⚠️ It is a LEGAL Commander deck, unlike the starter deck (D43), and that is
// asserted in `botPool.node.test.ts` rather than claimed here. It is also a
// weak one — no enchantments, no planeswalkers, no triggered abilities, no
// tutors, no recursion, because the engine runs none of those yet. That ceiling
// is the honest state of the app and it rises as the engine's coverage does.
//
// commander: Adun Oakenshield (BGR), chosen from 49 fully-executable legendary creatures for reaching 986 cards
// mv 0–1: wanted 6, took 6
// mv 2–2: wanted 14, took 14
// mv 3–3: wanted 14, took 14
// mv 4–4: wanted 12, took 12
// mv 5–5: wanted 8, took 8
// mv 6–6: wanted 5, took 5
// mv 7–∞: wanted 3, took 3
// lands: 37 nonbasic + 0 basic = 37
// main: 99 cards

export const BOT_DECK = {
  commander: "Adun Oakenshield",
  main: [
  "Diregraf Ghoul",
  "Icehide Golem",
  "Battlegrowth",
  "Brute Force",
  "Bull Rush",
  "Darksteel Relic",
  "Gifted Aetherborn",
  "Aggressive Urge",
  "Antagonize",
  "Arcane Signet",
  "Ark of Blight",
  "Breath of Fire",
  "Charcoal Diamond",
  "Coldsteel Heart",
  "Cunning Maneuver",
  "Dark Deed",
  "Dark Remedy",
  "Death in the Family",
  "Defeat",
  "Dragon Fodder",
  "Vampire Nighthawk",
  "Force of Savagery",
  "Afflict",
  "Appetite for the Unnatural",
  "Arcane Encyclopedia",
  "Auger Spree",
  "Bathe in Dragonfire",
  "Blight Rot",
  "Bloodstone Cameo",
  "Bombard",
  "Break Down",
  "Commune with Evil",
  "Crack Open",
  "Darksteel Ingot",
  "Bake into a Pie",
  "Bee Sting",
  "Carrion Call",
  "Caustic Rain",
  "Concentrated Fire",
  "Craterize",
  "Deadly Derision",
  "Drain the Well",
  "Electrify",
  "Elven Cache",
  "Engulfing Eruption",
  "Eviscerate",
  "Gigantosaurus",
  "Terrian, World Tyrant",
  "Cleansing Screech",
  "Command the Storm",
  "Contract Killing",
  "Dark Nourishment",
  "Demon's Grasp",
  "Dosan's Oldest Chant",
  "Yargle and Multani",
  "Quakestrider Ceratops",
  "Bounty of Might",
  "Desert Twister",
  "Explosive Impact",
  "Sire of Seven Deaths",
  "Aladdin's Ring",
  "Cinder Storm",
  "Adventurer's Inn",
  "Akoum Refuge",
  "Badlands",
  "Bayou",
  "Blackcleave Cliffs",
  "Bleeding Woods",
  "Blood Crypt",
  "Blooming Marsh",
  "Cinder Barrens",
  "Cinder Glade",
  "Command Tower",
  "Copperline Gorge",
  "Darkmoss Bridge",
  "Darksteel Citadel",
  "Deathcap Glade",
  "Deserted Temple",
  "Dragonskull Summit",
  "Drossforge Bridge",
  "Dryad Arbor",
  "Exotic Orchard",
  "Foul Orchard",
  "Geothermal Bog",
  "Gohn, Town of Ruin",
  "Golgari Guildgate",
  "Gongaga, Reactor Town",
  "Great Furnace",
  "Gruul Guildgate",
  "Haunted Mire",
  "Haunted Ridge",
  "Highland Forest",
  "Highland Weald",
  "Luxury Suite",
  "Overgrown Tomb",
  "Radiant Fountain",
  "Rakdos Guildgate",
  "Razortrap Gorge",
  "Reflecting Pool",
  ],
} as const;
