// GENERATED by src/data/botPool.node.test.ts — DO NOT EDIT BY HAND.
//
// Regenerate:  CRT_WRITE_BOT_DECK=1 npx vitest run src/data/botPool.node.test.ts
//
// The deck a bot seat plays. Every card in it is one the engine runs COMPLETELY
// — see `engineComplete.ts` — because a bot cannot read a card and apply it by
// hand the way a human can, so a card the app only partly runs is a card the bot
// must never draw.
//
// ⚠️ It is a LEGAL Commander deck, unlike the starter deck (D43), and that is
// asserted in `botPool.node.test.ts` rather than claimed here. It is also a
// weak one — no enchantments, no planeswalkers, no triggered abilities, no
// tutors, no recursion, because the engine runs none of those yet. That ceiling
// is the honest state of the app and it rises as the engine's coverage does.
//
// commander: Emmara, Soul of the Accord (GW), chosen from 479 fully-executable legendary creatures for reaching 5602 cards
// mv 0–1: wanted 6, took 6
// mv 2–2: wanted 14, took 14
// mv 3–3: wanted 14, took 14
// mv 4–4: wanted 12, took 12
// mv 5–5: wanted 8, took 8
// mv 6–6: wanted 5, took 5
// mv 7–∞: wanted 3, took 3
// lands: 37 nonbasic + 0 basic = 37
// main: 99 cards

export const BOT_DECK = {
  commander: "Emmara, Soul of the Accord",
  main: [
  "Rogue Elephant",
  "Scythe Tiger",
  "Skyshroud Ridgeback",
  "Straw Golem",
  "Glint Hawk",
  "Battlefield Raptor",
  "Bayou Groff",
  "Burdened Stoneback",
  "Plant Elemental",
  "+2 Mace",
  "Absolute Grace",
  "Absolute Law",
  "Abzan Advantage",
  "Acridian",
  "Adamant Will",
  "Adaptive Omnitool",
  "Aegis of the Heavens",
  "Aeolipile",
  "Aerial Boost",
  "Aerial Maneuver",
  "Bloated Contaminator",
  "Cradle Guard",
  "Force of Savagery",
  "Groundbreaker",
  "Soaring Stoneglider",
  "Abolish",
  "Accelerated Evolution",
  "Acrobatic Maneuver",
  "Adventurer's Airship",
  "Aerial Assault",
  "Aerial Predation",
  "Afterlife",
  "Air Response Unit",
  "Airship Crash",
  "Colossal Rattlewurm",
  "Runaway Carriage",
  "Thoughtweft Trio",
  "Advent of the Wurm",
  "Ajani, Adversary of Tyrants",
  "Ajani's Influence",
  "Allied Reinforcements",
  "Altar's Light",
  "Angel's Mercy",
  "Angelic Accord",
  "Arcane Spyglass",
  "Armageddon",
  "Endless Wurm",
  "Gigantosaurus",
  "Agonasaur Rex",
  "Baneslayer Angel",
  "Lyra Dawnbringer",
  "Primeval Force",
  "Terrian, World Tyrant",
  "Elder Gargaroth",
  "Quakestrider Ceratops",
  "Aggressive Mammoth",
  "Force of Nature",
  "Terra Stomper",
  "A Realm Reborn",
  "Sire of Seven Deaths",
  "Akroma, Angel of Wrath",
  "Ghalta, Stampede Tyrant",
  "Abandoned Air Temple",
  "Abandoned Outpost",
  "Abundant Countryside",
  "Access Tunnel",
  "Adventurer's Inn",
  "Ally Encampment",
  "Amonkhet Raceway",
  "Ancient Den",
  "Ancient Tomb",
  "Ancient Ziggurat",
  "Arch of Orazca",
  "Archaeological Dig",
  "Archway Commons",
  "Arctic Flats",
  "Arctic Treeline",
  "Arid Mesa",
  "Ash Barrens",
  "Avengers Tower",
  "Avishkar Raceway",
  "Bad River",
  "Baldur's Gate",
  "Bant Panorama",
  "Base Camp",
  "Birnin Zana Plaza",
  "Blasted Landscape",
  "Blighted Woodland",
  "Blinkmoth Well",
  "Bloodstained Mire",
  "Blossoming Sands",
  "Bonders' Enclave",
  "Botanical Plaza",
  "Bountiful Promenade",
  "Bretagard Stronghold",
  "Brokers Hideout",
  "Brushland",
  "Buried Ruin",
  "Cabaretti Courtyard",
  ],
} as const;
