// GENERATED by src/data/botPool.node.test.ts — DO NOT EDIT BY HAND.
//
// Regenerate:  CRT_WRITE_BOT_DECK=1 npx vitest run src/data/botPool.node.test.ts
//
// The deck a bot seat plays. Every card in it is one the engine runs COMPLETELY
// — see `engineComplete.ts` — because a bot cannot read a card and apply it by
// hand the way a human can, so a card the app only partly runs is a card the bot
// must never draw.
//
// ⚠️ It is a LEGAL Commander deck, unlike the starter deck (D43), and that is
// asserted in `botPool.node.test.ts` rather than claimed here. It is also a
// weak one — no enchantments, no planeswalkers, no triggered abilities, no
// tutors, no recursion, because the engine runs none of those yet. That ceiling
// is the honest state of the app and it rises as the engine's coverage does.
//
// commander: Adun Oakenshield (BGR), chosen from 71 fully-executable legendary creatures for reaching 1872 cards
// mv 0–1: wanted 6, took 6
// mv 2–2: wanted 14, took 14
// mv 3–3: wanted 14, took 14
// mv 4–4: wanted 12, took 12
// mv 5–5: wanted 8, took 8
// mv 6–6: wanted 5, took 5
// mv 7–∞: wanted 3, took 3
// lands: 37 nonbasic + 0 basic = 37
// main: 99 cards

export const BOT_DECK = {
  commander: "Adun Oakenshield",
  main: [
  "Diregraf Ghoul",
  "Icehide Golem",
  "Artifact Blast",
  "Aspect of Hydra",
  "Assault Strobe",
  "Barrage of Expendables",
  "Gifted Aetherborn",
  "Accelerate",
  "Aggressive Instinct",
  "Aggressive Urge",
  "Alesha's Legacy",
  "Ancestors' Aid",
  "Antagonize",
  "Arcane Signet",
  "Ark of Blight",
  "Back to Nature",
  "Battle Hymn",
  "Battle-Rage Blessing",
  "Bile Blight",
  "Bite Down",
  "Vampire Nighthawk",
  "Force of Savagery",
  "Acidic Soil",
  "Afflict",
  "Ambuscade",
  "An-Havva Inn",
  "Appetite for the Unnatural",
  "Arcane Encyclopedia",
  "Auger Spree",
  "Aura Barbs",
  "Awaken the Bear",
  "Bathe in Dragonfire",
  "Bedevil",
  "Bestow Greatness",
  "Agonizing Syphon",
  "Ambition's Cost",
  "Anarchy",
  "Ancient Craving",
  "Arms of Hadar",
  "Artisan's Sorrow",
  "Ashen Powder",
  "Bake into a Pie",
  "Beast Hunt",
  "Bee Sting",
  "Blood Mist",
  "Blood Tithe",
  "Gigantosaurus",
  "Doom Whisperer",
  "Terrian, World Tyrant",
  "Accelerated Mutation",
  "Apocalypse",
  "Blood Rites",
  "Bountiful Harvest",
  "Breath of Malfegor",
  "Yargle and Multani",
  "Quakestrider Ceratops",
  "Blastfire Bolt",
  "Book of Rass",
  "Bounty of Might",
  "Sire of Seven Deaths",
  "Aladdin's Ring",
  "Alpha Brawl",
  "Adventurer's Inn",
  "Akoum Refuge",
  "Badlands",
  "Bayou",
  "Blackcleave Cliffs",
  "Bleeding Woods",
  "Blood Crypt",
  "Bloodfell Caves",
  "Blooming Marsh",
  "Boiling Rock Prison",
  "Cinder Barrens",
  "Cinder Glade",
  "Command Tower",
  "Commercial District",
  "Copperline Gorge",
  "Darkmoss Bridge",
  "Darksteel Citadel",
  "Deathcap Glade",
  "Deserted Temple",
  "Dragonskull Summit",
  "Drossforge Bridge",
  "Dryad Arbor",
  "Dunes of the Dead",
  "Dwarven Mine",
  "Exotic Orchard",
  "Foggy Bottom Swamp",
  "Foul Orchard",
  "Foundry of the Consuls",
  "Gargoyle Castle",
  "Geothermal Bog",
  "Gingerbread Cabin",
  "Gnottvold Slumbermound",
  "Gods' Eye, Gate to the Reikai",
  "Gohn, Town of Ruin",
  "Golgari Guildgate",
  "Gongaga, Reactor Town",
  "Great Furnace",
  ],
} as const;
