// GENERATED by src/data/emblemTable.node.test.ts — DO NOT EDIT BY HAND.
//
// Regenerate:  CRT_WRITE_EMBLEM_TABLE=1 npx vitest run src/data/emblemTable.node.test.ts
//
// D475 - every emblem a Commander-legal card gives (`You get an emblem with "..."`), resolved to the ONE emblem
// printing whose text is the quote, and baked ONLY when that printing is engine-complete - the quote is the card's
// own text (D90; D473's rule for a quoted token), so the emblem's abilities must RUN from the command zone before
// the card may read whole. Keyed by the quoted text verbatim.
//
// ⚠️ A quote absent from here is one the resolver REFUSED: no such emblem, two of them, or one the engine does not
// run yet. `effectParse` treats it as a sentence it did not understand, which is the only safe answer (D90).

import type { TokenRef } from './tokenTable';

export const EMBLEM_TABLE: Readonly<Record<string, TokenRef>> = {
  "At the beginning of your end step, create a 9/9 blue Kraken creature token.": {"oracleId":"1a7523ff-8683-4187-bea7-edee70392791","printingId":"e45f7850-2ebb-4530-9859-f87b4e0e27be","name":"Kiora, the Crashing Wave Emblem"},
  "At the beginning of your end step, create three 1/1 white Cat creature tokens with lifelink.": {"oracleId":"7c0edef3-5346-4001-87ae-11157be58031","printingId":"1c97e5b2-a024-4aa7-a9b8-45f441aad138","name":"Ajani, Adversary of Tyrants Emblem"},
  "Creatures you control get +1/+0.": {"oracleId":"b34f4427-836d-4e8a-bb7c-1df41f0ea6b0","printingId":"327ddaaf-b6a7-4c80-9b38-5ab68181b3d6","name":"Sorin, Lord of Innistrad Emblem"},
  "Creatures you control get +1/+1.": {"oracleId":"a9b9c74d-551b-4939-bdd6-21afa2cf0931","printingId":"cd8be597-f402-4fb0-9135-897c4a0946f6","name":"Gideon, Ally of Zendikar Emblem"},
  "Creatures you control get +2/+2 and have flying.": {"oracleId":"2f12324a-e14e-4776-bc51-9fd42aaf3222","printingId":"177c37bd-c53d-43b2-88c4-0b80d17a5744","name":"Elspeth, Sun's Champion Emblem"},
  "Creatures you control get +2/+2 and have vigilance, trample, and indestructible.": {"oracleId":"de4fe6a3-0ea4-4745-9028-59e078331633","printingId":"1cf97003-eef0-4c01-aee1-8a8264d8ef95","name":"Vivien Reid Emblem"},
  "Creatures you control get +3/+3 and have trample.": {"oracleId":"6a5090b1-5eb6-4709-8208-ff3678be5756","printingId":"d6c65749-1774-4b36-891e-abf762c95cec","name":"Garruk, Cursed Huntsman Emblem"},
  "Creatures you control have double strike, trample, hexproof, and haste.": {"oracleId":"b7dc9439-d9bb-435a-8d3b-9e92bfae16ef","printingId":"1612f546-1bdb-4861-966c-4eeb7d1e65e8","name":"Domri Rade Emblem"},
  "Whenever an artifact you control becomes tapped, draw a card.": {"oracleId":"064b0e1a-3423-49eb-97f0-7d8690e38d4e","printingId":"bdb4fa32-18dd-4530-a529-5477e45413dd","name":"Tezzeret, Betrayer of Flesh Emblem"},
  "Whenever an artifact you control enters, this emblem deals 3 damage to any target.": {"oracleId":"99267d28-b231-446f-b2cc-236d3ed1ed80","printingId":"343d2622-a5a6-4195-ab41-c6bd17e334a2","name":"Chandra, Spark Hunter Emblem"},
  "Whenever you cast a noncreature spell, this emblem deals 2 damage to any target.": {"oracleId":"4facff15-09ea-47ed-845c-a41abb49e089","printingId":"0e573150-9f7e-4398-8997-aecb6057a020","name":"Narset of the Ancient Way Emblem"},
  "Whenever you cast a spell, exile target permanent.": {"oracleId":"8808b6bf-8fca-494d-9dd3-6f95c9c6605a","printingId":"c9ad6e7a-8ad8-4a35-b6c9-151720d88af9","name":"Venser, the Sojourner Emblem"},
  "Whenever you cast a spell, this emblem deals 5 damage to any target.": {"oracleId":"1c944fa3-ff6c-4638-a8cd-77d3ca68e599","printingId":"3143984b-9798-4062-9a91-8ee139c3448e","name":"Chandra, Torch of Defiance Emblem"},
};
