// GENERATES `src/data/tokenTable.ts`, and guards that it is still right.
//
// ⚠️ THIS IS OPTION (B) FROM D132: the description → printing resolution is
// baked at BUILD TIME, so `effectMode` stays a property of the CARD rather than
// of whoever else is at the table. What it is NOT is the literal form D132
// sketched — storing the printing id on `CardData` inside the card-database
// ingest — and the reason is structural: `electron/` never imports `src/` (a
// grep proves it), so the ingest is standalone CommonJS and could only resolve
// tokens with a SECOND COPY of `tokenParse.ts` in CJS. That is the duplication
// this project has written down five times (the Command Tower lesson, D122,
// D127, D129, D131). A generated TypeScript table is the same idiom as
// `botDeck.ts` and `fixtures/engineCards.ts`, costs no schema change, no
// re-sync, no fixture churn and no growth in the wire dictionary (D52), and
// bakes exactly the same answer. See D133.
//
// Regenerate:
//   CRT_WRITE_TOKEN_TABLE=1 npx vitest run src/data/tokenTable.node.test.ts

import { createReadStream, existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { createInterface } from 'node:readline';
import { describe, expect, test } from 'vitest';
import type { CardData } from './cardTypes';
import { parseTokenClause, resolveToken, specKey } from './tokenParse';
import { TOKEN_TABLE, type TokenRef } from './tokenTable';

const DATA_DIR = process.env.CRT_DATA_DIR ?? join(homedir(), '.commanders-roundtable');
const NDJSON = join(DATA_DIR, 'cards', 'cards.ndjson');
const HAVE_DB = existsSync(NDJSON);
const WRITE = process.env.CRT_WRITE_TOKEN_TABLE === '1';
const OUT = join(process.cwd(), 'src', 'data', 'tokenTable.ts');

/**
 * Every token description any Commander-legal card prints, resolved.
 *
 * ⚠️ Keyed by the DESCRIPTION, not by the card. Two cards that say "create a
 * 1/1 white Soldier creature token" name the same token, so the table is a few
 * hundred entries rather than a few thousand — and a card that is reworded into
 * an existing description costs nothing.
 */
async function build(): Promise<Record<string, TokenRef>> {
  const byName = new Map<string, CardData[]>();
  const clauses = new Set<string>();

  const rl = createInterface({ input: createReadStream(NDJSON), crlfDelay: Infinity });
  for await (const line of rl) {
    if (line === '') continue;
    let card: CardData;
    try {
      card = JSON.parse(line) as CardData;
    } catch {
      continue;
    }
    if (card.layout === 'token') {
      const list = byName.get(card.name) ?? [];
      list.push(card);
      byName.set(card.name, list);
      continue;
    }
    if (card.commanderLegality !== 'legal') continue;
    for (const face of card.faces) {
      for (const l of (face.oracleText ?? '').split(/\n|(?<=\.)\s+/)) {
        if (/\btokens?\b/i.test(l)) clauses.add(l.trim());
      }
    }
  }

  const out: Record<string, TokenRef> = {};
  for (const clause of clauses) {
    const spec = parseTokenClause(clause);
    if (!spec) continue;
    const hit = resolveToken(spec, byName.get(spec.name) ?? []);
    if (!hit) continue;
    // ⚠️ Last write wins is fine and cannot differ: `resolveToken` refuses
    // anything that resolves to two oracle ids, so one key can only ever reach
    // one token — and the PRINTING it picks is deterministic too.
    out[specKey(spec)] = { oracleId: hit.oracleId, printingId: hit.scryfallId, name: hit.name };
  }
  return out;
}

function render(table: Record<string, TokenRef>): string {
  const keys = Object.keys(table).sort();
  const rows = keys
    .map((k) => {
      const t = table[k] as TokenRef;
      return `  ${JSON.stringify(k)}: ${JSON.stringify(t)},`;
    })
    .join('\n');
  return `// GENERATED by src/data/tokenTable.node.test.ts — DO NOT EDIT BY HAND.
//
// Regenerate:  CRT_WRITE_TOKEN_TABLE=1 npx vitest run src/data/tokenTable.node.test.ts
//
// Every token description any Commander-legal card prints, resolved to the ONE
// printing it names. Keyed by \`specKey\` from \`tokenParse.ts\`, so the generator
// and \`effectParse\` cannot disagree about what "the same description" means.
//
// ⚠️ THE RESOLUTION IS BAKED HERE so \`effectMode\` stays a property of the CARD
// (D132's option B, D133). Resolving at runtime instead would make whether a
// spell executes depend on which token printings happened to be in the game's
// pool — and \`tier3.ts\` would then tell a player something the engine
// contradicts, which is D122's exact failure.
//
// ⚠️ A description absent from here is one the resolver REFUSED: unreadable,
// naming no printed token, or naming two. \`effectParse\` treats it as a sentence
// it did not understand, which is the only safe answer (D90).

export interface TokenRef {
  readonly oracleId: string;
  readonly printingId: string;
  /** The token's printed name, for the log and for loading it into a game. */
  readonly name: string;
}

export const TOKEN_TABLE: Readonly<Record<string, TokenRef>> = {
${rows}
};
`;
}

describe.skipIf(!HAVE_DB)('the baked token table', () => {
  let built: Record<string, TokenRef>;

  test('reads the whole database', async () => {
    built = await build();
    expect(Object.keys(built).length).toBeGreaterThan(100);
    if (WRITE) {
      writeFileSync(OUT, render(built), 'utf8');
      // eslint-disable-next-line no-console
      console.log(`Wrote ${Object.keys(built).length} token descriptions → ${OUT}`);
    }
  }, 600_000);

  /**
   * ⚠️ **REGENERATING MUST BE A NO-OP**, and this is the guard D123 established
   * and D130 caught `botDeck.ts` missing. A semantic check ("every entry names a
   * real token") passes happily on a table the generator would no longer
   * produce. Comparing the exact bytes catches a rewording, a new set, a dropped
   * entry and a hand edit of a file that says DO NOT EDIT BY HAND, all at once.
   */
  test('regenerating the committed table would change nothing', () => {
    const committed = JSON.stringify(TOKEN_TABLE, Object.keys(TOKEN_TABLE).sort());
    const fresh = JSON.stringify(built, Object.keys(built).sort());
    expect(fresh).toBe(committed);
  });

  /** A canary on the table itself: an empty one would satisfy every other check. */
  test('the table is the size it is', () => {
    expect(Object.keys(TOKEN_TABLE).length).toBe(Object.keys(built).length);
    expect(Object.keys(TOKEN_TABLE).length).toBeGreaterThan(300);
  });
});

describe.skipIf(HAVE_DB)('the baked token table', () => {
  test('SKIPPED — no card database', () => {
    // eslint-disable-next-line no-console
    console.warn(`No card database at ${NDJSON}. Run: node electron/cardsvc-worker.cjs --sync`);
    expect(HAVE_DB).toBe(false);
  });
});
